### ISSUE TITLE
Installation on ATLAS 617 - But upgraded from previous script

### ISSUE THREAD

**Issue by kotakSempit** [xeon1989/Proton-X50-APK-Installer-ATLAS#1]
Hi. My HU already upgraded to ATLAS ver 617 (FS). But before upgrading, I used previous script to sideload app into GKUI. Without uninstall the sideloaded app, I upgrade to ATLAS. But just now, I've tried this latest script. Nothing happened. Is this related to this notice you mentioned in readme? 

> If you installed apps with any method other than this Installation Script, please DO NOT PROCEED with this script. The Installation / Uninstallation script WILL NOT WORKS as it is not compatible.

**Comment by xeon1989** [comment]
After upgrading to 617, your sideloaded apps still intact or got wiped out?

**Comment by kotakSempit** [comment]
Got wiped out I think, since only ATLAS app is available in the app drawer. But I did open the engineering mode and export the log. From the log, it seems the installed files/apk still exists, but cannot be registered in the ATLAS launcher due to error in manifest or something like that (Already forgot the exact error mentioned in the log file).

**Comment by xeon1989** [comment]
Mine to share the log and output file?

**Comment by kotakSempit** [comment]
Hi. Just for an update, the script works. Just need to change to another USB drive. Using Kingston, now it work. Thank you!

**Comment by xeon1989** [comment]
> Hi. Just for an update, the script works. Just need to change to another USB drive. Using Kingston, now it work. Thank you!

Thanks for the heads up!
