### ISSUE TITLE
YouTube Video Resolution Issue

### ISSUE THREAD

**Issue by Roychun12** [xeon1989/Proton-X50-APK-Installer-ATLAS#11]
Issue that I noticed that when first time opening the YouTube, it can make it full screen( as it enabled fit to screen option in settings). After clicked the three dots at top right corner, the screen exited and resolution of the current running video shrunk. Cannot make it back the video to fit to screen even thought in YouTube settings the option fit to screen still enabled. The only solution to make it full screen is need to clear data for YouTube in apps settings. By doing this it makes the YouTube to refresh new and can use it like first time. But when we off the x50 and restart back the YouTube video cannot make it to fit to screen. 

So two things I noticed here.  

1) each time when start X50 need to clear data of YouTube in apps settings to make it full screen. 

2) After that do not accidentally click the three dots at top right corner in the YouTube video to open the quality settings (by clicking this 3 dots it exits from the YouTube and can’t make it fit to screen). Have to reset again from 1). 
Please look into this ya!!!

**Comment by xeon1989** [comment]
Could you please confirm if issue persists? 
I am testing Youtube Vanced, not sure if the same still happening on YT premium.
