### ISSUE TITLE
YouTube Music playlist not populated (Apple Carplay)

### ISSUE THREAD

**Issue by nukm4n** [xeon1989/Proton-X50-APK-Installer-ATLAS#13]
Hello,

Not sure this issue is specific to the script or it is Carplay's own issue.

When choosing YouTube Music on Carplay, go to Library --> Playlist = will only see "Liked Songs"

I have many playlists created in YouTube / YouTube Music, but they are not populated in the Playlist list

The workaround:

1.  Play your preferred playlist on your YouTube Music app on your phone / YouTube Music web.
2.  You will see your recent playlists under Recently Opened in the Carplay

End.

**Comment by xeon1989** [comment]
Hi, do you see the same or different behavior with AA of other headunit?
I tried tried the same phone with other car's Android OEM headunit, same behavior.
No chance try on car with natively supported AA yet.
