### ISSUE TITLE
Error: Activity not started, unable to resolve Intent { act=ecarx.settings/android.intent.action.MAIN flg=0x10000000 }

### ISSUE THREAD

**Issue by arif-mustaffa** [xeon1989/Proton-X50-APK-Installer-ATLAS#14]
Hi sir, I try installing this script on my X50, and I got this error
```
Error: Activity not started, unable to resolve Intent { act=ecarx.settings/android.intent.action.MAIN flg=0x10000000 }
```
Details output can be seen here
[outputUninstall_1677039890.txt](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/files/10801474/outputUninstall_1677039890.txt)

Anything that I do wrong?

**Comment by xeon1989** [comment]
Hi, you ran Uninstallation script.
Please try again with Installation script.

**Comment by xeon1989** [comment]
Hi, I saw a lot of ._* files.
Did you prepared your usb on Mac?
Try follow instructions in this issue to clean up files, or prepare the files on Windows.

https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/issues/5

**Comment by kennardlee** [comment]
Hi, silly me. Indeed issue coming from MacOs(After i read comments from fevernova90). The power of cummunity! Thanks Xeon for your dedication and hard work!

**Comment by arif-mustaffa** [comment]
Thanks. I was preparing files on Mac also. Will retry again later.
