### ISSUE TITLE
X50 Carplay

### ISSUE THREAD

**Issue by JiFong01** [xeon1989/Proton-X50-APK-Installer-ATLAS#15]
How can control the CarPlay music using steering. I tried change the audio channel to BT. But the music output was come out from my phone, not from car speaker.

**Comment by jctang1028** [comment]
https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/blob/main/SteeringButtonWorkaroundAA.md

this workaround may help you, you need to launch “Media” first before connect to CarPlay
