### ISSUE TITLE
Manage to Install few applications only

### ISSUE THREAD

**Issue by merangg** [xeon1989/Proton-X50-APK-Installer-ATLAS#16]
After finishing installing using the script. Just found that only auto kit and youtube premium were installed. Try to check the log file. But unreadable

[outputInstall_1677319234.txt](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/files/10830807/outputInstall_1677319234.txt)

**Comment by xeon1989** [comment]
Looking at the log, it seems corrupted.
Please Uninstall and install again.
