### ISSUE TITLE
CarPlay freezes

### ISSUE THREAD

**Issue by ky0112** [xeon1989/Proton-X50-APK-Installer-ATLAS#17]
CarPlay freezes after exit autokit and re-enter autokit app.

**Comment by xeon1989** [comment]
Hi, have you tried this?

https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/issues/3#issuecomment-1436034398

**Comment by ky0112** [comment]
> Hi, have you tried this?
> 
> [#3 (comment)](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/issues/3#issuecomment-1436034398)

hi Xeon, after tried that setting it work. Once the render mode changed to default, CarPlay icon become smaller. So I played with the setting to scale up the icon in CarPlay. Follow is my setting hope it help the x50 community.

1: Application setting > resolution > 1440x480 (scale up the CarPlay icon, this because of render mode)
2: Application setting > frame rate > 25
3: Advanced settings > bottom navigation bar > show (to display the original proton home bar)
4: Advanced settings > render mode > default 
![BD732C5A-33E5-4B50-890D-9B0122364667](https://user-images.githubusercontent.com/69720368/221472879-9be3bd19-0911-4d80-8451-9501a9b1a145.jpeg)


thanks Xeon :)
