### ISSUE TITLE
Do we need to upgrade autokit version?

### ISSUE THREAD

**Issue by revolutionaries9** [xeon1989/Proton-X50-APK-Installer-ATLAS#18]
Hi. Do we need to update the autokit version? I attempted to update and failed and now only the autokit is unable to installed. Other apps is still available. I want to use AC , so can I just reinstall back the file? Kindly help. Tq

**Comment by xeon1989** [comment]
Hi, may I know if Autokit still usable after update failed?
Nevertheless, you try following script to:
1. Format USB drive and fill it with files in "1. uninstall" folder. Plug it to IHU and wait for the uninstallation and reboot.
2. Repeat step 1 with files in "2. install" folder.

**Comment by xeon1989** [comment]
Please try to reinstall with provided steps, let me know if it helps.

**Comment by revolutionaries9** [comment]
Okay will do. Thank you

**Comment by revolutionaries9** [comment]
Hi. I managed to uninstall and reinstall back the file and autokit is able to use. But i have 2 problem: 

1) when connect the the AC, spotify is auto playing, anyone knows how to turn it this off?
2) the sound is coming from the phone instead of the car speaker. Can anyone help pls? Thank you

**Comment by naffy2k** [comment]
> Hi. No. The autokit apps logo still available but when i press it, it says that Autokit apps are not installed.
> 
> Tq for the reply.

also same thing happened to me after update failed. but apparently instead of uninstall/reinstall you can just force restart the IHU by long pressing the power button >15 seconds then AutoKit will be able to open like before updating

**Comment by syh9849** [comment]
I followed the steps to uninstall and reinstall to the latest version 2022.11.15.1535. Downloaded the upgrade but failed to install, need to restart IHU to open the app again. Im using Carlinkit 4.0 CPC200-CP2A, the screen still show 'Please insert the device'. Does anyone have solution for this?

**Comment by jctang1028** [comment]
> I followed the steps to uninstall and reinstall to the latest version 2022.11.15.1535. Downloaded the upgrade but failed to install, need to restart IHU to open the app again. Im using Carlinkit 4.0 CPC200-CP2A, the screen still show 'Please insert the device'. Does anyone has solution for this?

If not mistake, cp2a only work for factory wired CarPlay car model 
Autokit only work for Ccpa, ccpm and ccpw this three types dongle

![Uploading E5101070-C1BD-4085-B0D4-349183A14CA8.png…]()
