### ISSUE TITLE
Android Auto crashes every 10-30 seconds

### ISSUE THREAD

**Issue by Asami42KZ** [xeon1989/Proton-X50-APK-Installer-ATLAS#20]
Hi xeon, i want to address my current issue with android auto that comes with your scripts. Few solutions i tried like using expensive data cable and original samsung cable. Both gives the same results of crashing. 

I'm using galaxy fold 4 with one ui v5.1 and android v13. Hope u can assist me as i really liked the AA

**Comment by PeterRob** [comment]
Try clearing HUR data - from memory you can access by using the hidden setting | applications.

**Comment by xeon1989** [comment]
@Asami42KZ Unfortunately I do not have Android 13 to try with.
It's looking fine on Android 12.
Please try to clear data as mentioned by @PeterRob, or you may also try if same happened on AA Wireless.

**Comment by zhafri** [comment]
Just OK with android 13 with OneUI 5.1 (samsung s20 fe)...use wireless AA

**Comment by Asami42KZ** [comment]
@PeterRob I tried clearing both data and cache of the HUR and AA in my phone. Sadly it doesnt work :(

**Comment by Asami42KZ** [comment]
@zhafri my only choice is AA wireless now, no crashes for wireless but very hectic to open hotspot, start server and go to HUR to start it manually.
