### ISSUE TITLE
Do i need to purchase android auto for this to work?

### ISSUE THREAD

**Issue by jwloqwe** [xeon1989/Proton-X50-APK-Installer-ATLAS#21]
Not sure if this is how it works? But do I need to purchase the HUR in order for this to work?

**Comment by xeon1989** [comment]
HuR included will works even without buying it.
But if would be great to purchase HuR to show our support as it is an awesome app.
Given it's feature, in my opinion it's not very expensive, I would recommend everyone to buy it.

**Comment by jwloqwe** [comment]
However once I had plugged in USB, there is no response from the head unit. Just stays at the screen USB device detected. Any thing that needs to be done before plugging in USB?

**Comment by xeon1989** [comment]
A few things you can do
- Make sure your HU running on version 617 / 618. 
- Check if you formatted your USB in FAT32
- Try USB with smaller capacity (32GB or lower)
- Make sure you extract the file from zip. Do not reuse the file after running it on other car.

If above steps not working, try other USB drive.

**Comment by xeon1989** [comment]
Hi @jwloqwe, did you just updated your IHU to version 617 / 618 recently?
It seems for those updated after 2-Mar-2023, the script won't works anymore.

**Comment by jwloqwe** [comment]
Yes indeed, updated after the 2nd of march recently. That's why

**Comment by xeon1989** [comment]
@jwloqwe unfortunately in your case, you can't use the script to install app.
