### ISSUE TITLE
Google pinyin apk

### ISSUE THREAD

**Issue by jctang1028** [xeon1989/Proton-X50-APK-Installer-ATLAS#22]
Can I use “Install Your Own Apps” to install Google pinyin? I had copy the “lib” folder but inside only have folder “x68_64”. Don’t have “arm” or “arm64” folder

**Comment by xeon1989** [comment]
Hi @jctang1028 , I'm not sure how would it work with other input method.
In your case, i believe you dont need to cooy anything from lib folder.

**Comment by jctang1028** [comment]
I tried, the input was installed but not working. When go to setting change the keyboard to Google pinyin, the keyboard won’t show up when search something

**Comment by muncheno** [comment]
> I tried, the input was installed but not working. When go to setting change the keyboard to Google pinyin, the keyboard won’t show up when search something
> 
> can I just uninstall specific apk only? Like Google pinyin was installed but not working, decide to uninstall it

If you attach you installations scripts / files here, I can make a specific removal script.

**Comment by jctang1028** [comment]
I uninstalled by using xeon uninstall script, which mean already uninstall whole thing🥲 now I’m gonna install all apps again

**Comment by muncheno** [comment]
Haha..no problem

**Comment by Micansaaron** [comment]
> I uninstalled by using xeon uninstall script, which mean already uninstall whole thing🥲 now I’m gonna install all apps again

did u work on reinstall all the apps ? i unistalled and tried to reinstall but it look unsuccesful. After all the script done it shows nonthing apps installed on HU.

**Comment by muncheno** [comment]
> > I uninstalled by using xeon uninstall script, which mean already uninstall whole thing🥲 now I’m gonna install all apps again
> 
> did u work on reinstall all the apps ? i unistalled and tried to reinstall but it look unsuccesful. After all the script done it shows nonthing apps installed on HU.

Please share the log file output XXX.txt for both uninstall and reinstallation. 
We can't tell what's wrong if you don't share.

**Comment by nyzam81** [comment]
sorry might be out of topic but for those APK withour the lib folder is ther any way to installed it using the script?

**Comment by xeon1989** [comment]
@nyzam81 just skip the lib folder part then

**Comment by jctang1028** [comment]
This version of google pinyin can install in ihu, the lib folder have arm folder, after installed need go to hidden setting to choose Google pinyin keyboard, finally can type chinese words!

https://m.apkpure.com/google-pinyin-input/com.google.android.inputmethod.pinyin/download/4520312-APK
