### ISSUE TITLE
how to downgrade atlas OS to GKUI 19

### ISSUE THREAD

**Issue by andrewleo013** [xeon1989/Proton-X50-APK-Installer-ATLAS#23]

**Comment by Warcheif81** [comment]
First thing we need to have is the last version of GKUI19 firmware in complete block of zip file (SW0SXRA0121L5167.00412)
If that firmware is ready we can put it in thumbdrive and straight away enable factory mode and trigger USB upgrade menu for downgrade process...
if anyone have made backup or pull that firmware from server previously can let us know...TQ..

**Comment by xeon1989** [comment]
@andrewleo013 In LYN there's member help to downgrade for little cost for petrol compensation or even free if you're at Melaka / Penang island.
