### ISSUE TITLE
Install and uninstall script for autokit only

### ISSUE THREAD

**Issue by jctang1028** [xeon1989/Proton-X50-APK-Installer-ATLAS#24]
Can create the script for install and uninstall autokit only? Since autokit cannot normal update, if autokit have update version I can uninstall the old version and install the new version. Thanks

**Comment by xeon1989** [comment]
Hi @jctang1028 , 

We would like to inform you that we have created a package containing the latest version of Autokit, which you may use to install the software.

[AutoKit_2023.02.27.1452.zip](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/files/11010121/AutoKit_2023.02.27.1452.zip)

Please be advised that you may also follow this [doc](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/blob/main/Install_Your_Own_Apps.md) to create the script for latest Autokit. However, the uninstaller provided in the earlier guide has the potential to remove all applications on your device. 

Nevertheless, the Uninstallation script included in the package we have provided is designed to remove only Autokit, ensuring that other installed apps will remain untouched.

Regards

**Comment by jctang1028** [comment]
thank you so much! @xeon1989

**Comment by xeon1989** [comment]
@houshen0806 I'm not CarPlay user so I have no idea.
The update was suggested by many other carlinkit user which they mentioned it fixes Update issue.
