### ISSUE TITLE
Atlas 581 APK Installer support

### ISSUE THREAD

**Issue by asdenhub** [xeon1989/Proton-X50-APK-Installer-ATLAS#25]
My IHU Atlas is still on unpatch firmware version. I plan on donating to https://ko-fi.com/xeon1989 if can become compatible on Atlas 581 version.

**Comment by xeon1989** [comment]
Hi, do you mind to take a picture of your IHU showing the system version and hardware version?

**Comment by asdenhub** [comment]
> Hi, do you mind to take a picture of your IHU showing the system version and hardware version?

Here's the version 

![IH unit](https://user-images.githubusercontent.com/129833669/229762309-dfad9cac-1775-4337-8628-dc2a5ade7df0.jpg)

**Comment by xeon1989** [comment]
Hi @asdenhub, as you noticed it's version 581 rather than 616.
It would require an upgrade to 617v1 for the script to works.

There is some ppl in LYN willing to help if you resides in Central region, Penang or Melaka.

**Comment by asdenhub** [comment]
> Hi @asdenhub, as you noticed it's version 581 rather than 616. It would require an upgrade to 617v1 for the script to works.
> 
> There is some ppl in LYN willing to help if you resides in Central region, Penang or Melaka.

It's fine if you don't know or plan to support 581 version. Thanks anyway!
