### ISSUE TITLE
Flasing Firmware updated

### ISSUE THREAD

**Issue by QayyumZulkifli** [xeon1989/Proton-X50-APK-Installer-ATLAS#30]
For PX50 Exec spec stuck after pressing SOC..the USB icon cannot be press...just black colour only..after that the MAC Address become N/A

**Comment by xeon1989** [comment]
Hi, if the USB button greyed out, it indicates the USB drive not detected. 
Might be the issue with USB drive or files.
It could be the drive not formatted with FAT32 file system, or the incorrect file placed in USB drive. 
Mind to share the picture of the USB icon, and file system + content of your USB drive?

**Comment by QayyumZulkifli** [comment]
![image](https://user-images.githubusercontent.com/126178941/232535086-7fdcc54f-f767-43cb-a80e-b4997f453c77.jpeg)

**Comment by QayyumZulkifli** [comment]
![image](https://user-images.githubusercontent.com/126178941/232536364-238361ae-ada0-484a-b997-3207623102e8.jpeg)

**Comment by ky960310** [comment]
> hi xeon..this i try for fs model...it's wrong paste for flashing firmware?

hi bro. you have to put the unzip file ( firmware )

![image](https://user-images.githubusercontent.com/131019179/232559309-97b45339-92a9-4ced-9730-b455c432f45d.png)

**Comment by QayyumZulkifli** [comment]
tqvm KY & xeon for the guide...succeed
