### ISSUE TITLE
Uninstallation script for Newpipe & Youtube vanced music

### ISSUE THREAD

**Issue by ky960310** [xeon1989/Proton-X50-APK-Installer-ATLAS#31]
Hello xeon, good day!  
I just found out some issue about the uninstall script. The uninstall script is not working on the newpipe and youtube vanced music. It can uninstall every apk that you provided but it cannot uninstall newpipe and youtube vanced music.  
Sorry I couldn't provide any output uninstall file here.

Thanks !

**Comment by xeon1989** [comment]
Hi Khay Yin, thanks for reporting the bug!
I have fixed the uninstaller, it should now uninstall all apps installed by my installation script or Custom App script. 
Feel free to give it a try, if you need it.
https://drive.google.com/file/d/1-Bm6H5dBCYvpLrAVeWJcQXEXnoMQVE1U/view?usp=share_link

Also, many thanks for actively supporting X50 owners in Facebook and other platform. 
I couldn't thank you enough for making their life easier. 

BR,
Chris
