### ISSUE TITLE
Uninstall script 

### ISSUE THREAD

**Issue by dc69696969** [xeon1989/Proton-X50-APK-Installer-ATLAS#32]
Good day Xeon, I’ve done extracting the files and plugged it in the car.

After 5 minutes, the IHU stays at the same setting page after wireless charging page. Is there something missing that you can enlighten me. Thank you in advance.

Pictures attached are after I plugged it in the car and then to my laptop. 

![Uploading IMG_3027.jpeg…]()

**Comment by xeon1989** [comment]
@dc69696969  i see the this issue closed, did you fixed the issue yourself?
