### ISSUE TITLE
Atlas new version released

### ISSUE THREAD

**Issue by jctang1028** [xeon1989/Proton-X50-APK-Installer-ATLAS#34]
![3b0a2bc9-8fca-4a41-831f-5b8966ede8ba](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/124884086/05cd6731-325f-4f6f-8621-4d74cabea73a)
![IMG_2369](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/124884086/d328f564-7628-486a-af2f-31152b7bc358)

I was wondering the new version of atlas can side load apps or not?
I know it can’t use the previous script but got different scripts or other ways to side load or not

**Comment by jctang1028** [comment]
Or maybe can use same script to side load😂 
Who tried it before?

**Comment by ky960310** [comment]
> Or maybe can use same script to side load😂 
> 
> Who tried it before?

I don't think the script is working for the new atlas 644 version it's not working for 617/618 v2 as well.
What I'm thinking is maybe we can flash the firmware ( downgrade) to 617/618 v1, after that only install the script.

**Comment by xeon1989** [comment]
Most likely no, anyone installed could give it a try.

**Comment by jctang1028** [comment]
what if I install the new version atlas but my previous sideload app gone, can I flash atlas to 617 version?

**Comment by xeon1989** [comment]
@jctang1028 theoretically yes, but I'm not sure if the steps will still the same as I haven't (probably never) get my hands on one.

**Comment by jctang1028** [comment]
I had installed the 644 version atlas, expected all side load app gone, but can flash firmware to downgrade to 617 version and everything back to normal.

**Comment by ky960310** [comment]
> I had installed the 644 version atlas, expected all side load app gone, but can flash firmware to downgrade to 617 version and everything back to normal. 

Good good 👍🏻👍🏻👍🏻👍🏻

**Comment by jctang1028** [comment]
@xeon1989 Don’t mention it. 
Let me sum up:
after updated to 644 version
Pros: (I think the only one pro😂)
- yes, the bluetooth is connect automatically 
Cons: 
- everything sideload apps gone
- Can’t use the 617 version script to sideload 

If anyone accidentally updated to 644 version, don’t worry cuz u can flash firmware downgrade to 617 version. Just need to take some time to do it.

**Comment by mfmf1998** [comment]
Hi @xeon1989 and all. I m new, here so bare with me yeah.. Hopefully can get some help and advice from u all. I want to ask abt the downgrade to 617v1. i went through the steps on how to downgrade but i m still quite scared to proceed. Are there any precautions or risks that i should be aware of ? what happens if the downgrade failed ? would the IHU go back to the previously installed FW ir 617v2 ? Many thanks and really appreciate ur time to provide some guidance :)

**Comment by xeon1989** [comment]
Hi @mfmf1998, I certainly understand your concern and worries. 
However, please bear in mind that any operation that changes default behavior of IHU came with risk.

The best case it does no change to your current IHU.
The worst could happen I can imagine now, in case there's interruption in firmware flashing, depending on what it does in that moment, system might be corrupted and that might brick you IHU. 
Therefore it's very important to follow the steps and make sure the process are not interrupted.

Nevertheless, the downgrade steps mentioned in guide are the way as how ACO and Proton SC perform the manual upgrades.
With many testimonies and no negative feedback so far,  the risk should be minimal provided you follow all precautions. 

Hope that clarify the risk and precautions.

**Comment by mfmf1998** [comment]
Yeah but knowing my luck in this kind of things, eventhough i go thru every steps carefully, there must be somewhere or somehow, something bad will happen and it ended up worse than what it is before haha.. 

That is why i am searching around for a backup plan on how to reinstall back the IHU FW incase my IHU got corrupted and broke.

**Comment by SCTang2023** [comment]
I hv upgraded to 644 version from GKUI 19...due to some reasons....so all the APKSs cannot be used and yet I couldn't downgrade to 617v1....or back to GKUI19....oh my.....hope the new version of sideloads apps for 644 will come out soon?

**Comment by xeon1989** [comment]
@jctang1028 confirmed that he able to downgrade to 617 after upgrade to 644.
Why you couldn't downgrade?

**Comment by SCTang2023** [comment]
Hmm...I've no idea. I follow the steps to flash ...but there is no available update version detected in usb drive...as I have already put the file in my usb?!....

**Comment by SCTang2023** [comment]
@jctang1028 
I tried again with the zipped file but still cannot.
![Uploading IMG_20230520_095146.jpg…]()

**Comment by SCTang2023** [comment]
![IMG_20230520_095146](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/134071872/01e171ed-24b2-4cb3-81ed-26d28ec69ca0)

**Comment by SCTang2023** [comment]
> 
I hv checked mine...the version is still 617. I hv changed to atlas 617 from GKUI19 yesterday......I need to flash if I want to install sideload apps, right? But i couldn't do it.....kindly advise.
![Uploading IMG_20230520_095146.jpg…]()

**Comment by ky960310** [comment]
> > 
> 
> I hv checked mine...the version is still 617. I hv changed to atlas 617 from GKUI19 yesterday......I need to flash if I want to install sideload apps, right? But i couldn't do it.....kindly advise.
> 
> ![Uploading IMG_20230520_095146.jpg…]()
> 
> 
> 
> 
> 
> 
> 
> 

Unzip the first flash firmware file only. The second one no need to unzip. Place the flash firmware file + installation script into your formatted pendrive. I recommend not more than 32GB PENDRIVE...![image](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/131019179/95572eeb-29ed-4ca1-8564-7cfe9390263f)

**Comment by ky960310** [comment]
> > 
> 
> I hv checked mine...the version is still 617. I hv changed to atlas 617 from GKUI19 yesterday......I need to flash if I want to install sideload apps, right? But i couldn't do it.....kindly advise.
> 
> ![Uploading IMG_20230520_095146.jpg…]()
> 
> 
> 
> 
> 
> 
> 
> 

Version 617/618 v1 no need to flash firmware. Just follow the installation script tutorial. 
Only flash firmware + installation script for version 617/618 v2.

I suggest you do the installation script first, if doesn't work on your ihu only try to flash firmware + install script.
Please take note that flash firmware may void your warranty and in case there's interruption in firmware flashing, depending on what it does in that moment, system might be corrupted and that might brick you IHU.

**Comment by SCTang2023** [comment]
> script

Thanks for Ur suggestions!
It works.

**Comment by kanasite** [comment]
@xeon1989 any method to actually check if the firmware is 617/618 v1 or v2?

**Comment by xeon1989** [comment]
@kanasite try insert usb with scripts. If it runs, it's 517v1

**Comment by kanasite** [comment]
lol, that's what I originally thought. Btw offtopic: will SC always update your IHU firmware when you sent back for service? (I noticed u disable the OTA apk, just wonder if it's something against their policy and can request them to ignore IHU?)

**Comment by Will33am** [comment]
may i know if we update to 644, previously disable apps on ver 617 will enable back by itself? Thanks

**Comment by Will33am** [comment]
> I had installed the 644 version atlas, expected all side load app gone, but can flash firmware to downgrade to 617 version and everything back to normal.

may i know if we update to 644, previously disable apps on ver 617 will enable back by itself? such as MAP, Weather n ETC. thx

**Comment by jctang1028** [comment]
@Will33am It won't appear those apps after updated, but u can do factory reset to enable back the disabled apps

**Comment by kanasite** [comment]
> 

@Will33am the good thing about @xeon1989 script is "disable" them, not "remove" them, so he also provided a "reset" script which basically enable back those apps he disabled in the optimisation script. For future firmware update we actually have no idea (ACOTech can decide to flash the new firmware and enable those apps). Personally I would rather run the "reset" script before "updating the latest firmware" just be on the safe side.

**Comment by Will33am** [comment]
Actually, I don’t wanna enable those apps back again. I just wanna confirm bfore i update.

**Comment by YogaDon** [comment]
Hi @xeon1989 I just wanna ask if this script would work for the latest SWX50RC1119H8AXH.00115 version??

**Comment by xeon1989** [comment]
@YogaDon No.

**Comment by Kushal95** [comment]
Hello @xeon1989,

Am from mauritius and just got a proton X50 RC with software version SWX50RC1119H8AXH.00115 as well.

The proton map doesn't work here as i can't even signup in the membership app. So it would be great if i could sideload atleast a waze or google map app.

I know lots of people who would also benefit from this. Is there any way that this can be done please?

**Comment by xeon1989** [comment]
Hi @Kushal95, this script only works for RA.
Script of RC is not in my plan unfortunately.
