### ISSUE TITLE
Autokit app shows black screen upon connected (Apple CarPlay)

### ISSUE THREAD

**Issue by johnchen99** [xeon1989/Proton-X50-APK-Installer-ATLAS#35]
- Uninstalled previous installation (old YouTube Premium)
- Disabled Proton default apps
- Lastly, Installed the latest installation script (with MicroG)

After the latest installation, I am encountering an issue which does not happen before. When Apple CarPlay auto-connected to the Autokit (Carlinkit) app, the app will show a blank black screen (able to navigate to other pages, but only the Autokit app shows a black screen). 

However, it can be solved by re-inserting the Carlinkit device/disconnecting my phone and reconnecting the CarPlay, which is quite troublesome before driving. 

Does anyone have a similar issue?

**Comment by johnchen99** [comment]
Picture of the screen after starting up my car, and after Autokit automatically starts up

![image](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/61832229/dcf51d08-513a-44a2-99c3-8700d3bf0ff2)

**Comment by johnchen99** [comment]
Solved by: 
- Remove all scripts and clear up everything
- Reset and restore IHU to default
- Disable default apps again
- Reinstall script

Carplay is back to normal for now, where it will auto-connect and show the proper interface

**Comment by ky960310** [comment]
Hi bro, you may try this setting if it happen to u again.

![image](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/131019179/9300cafc-5f8e-4779-9ea0-313e3a0d870f)

**Comment by johnchen99** [comment]
> Hi bro, you may try this setting if it happen to u again.
> 
> ![image](https://user-images.githubusercontent.com/131019179/241408172-9300cafc-5f8e-4779-9ea0-313e3a0d870f.png)

Yes, the settings were exactly the same before I reinstall, currently all good after reinstalling, but experienced 1-2 times freezes till now. Was not there before I updated to the latest script.
