### ISSUE TITLE
Google Maps Location issue

### ISSUE THREAD

**Issue by RadenAmzar** [xeon1989/Proton-X50-APK-Installer-ATLAS#36]
Hi. I’m having issue where Google Maps unable to detect my location. I already confirm the permission is allowed. Attached are the screenshot. Thanks!
![IMG_0878](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/130873979/ecb78b3f-f46f-4c65-af2f-ed8610ae1432)
![IMG_0879](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/130873979/1b7ec5cf-ad91-45fb-b62e-7a1625902f4e)

**Comment by xeon1989** [comment]
Unfortunately i never face this issue. Leaving this open for others to comment.

**Comment by RadenAmzar** [comment]
I solved it by reinstalling everything back. Thanks.
