### ISSUE TITLE
Any optimization script for GKUI ??

### ISSUE THREAD

**Issue by Nicchua89** [xeon1989/Proton-X50-APK-Installer-ATLAS#37]
Hi Chris, thanks for your effort to x50 community. Is there any optimization script or disable app  script to made GKUI run even smoother?  I prefer stick with GKUI but sometimes GKUI run a bit slower, too much useless default app. 

Thanks.

**Comment by xeon1989** [comment]
Do you have any specific app to disable in your mind?

**Comment by Nicchua89** [comment]
> Do you have any specific app to disable in your mind?

Thanks for your reply. 
Maybe same as Atlas ?? 😂 Because my car spec is standard version, member center and some others like maps or weather app macam useless for me 🤣

**Comment by xeon1989** [comment]
Sorry for my super late response.
Try these scripts.

You may optimize by disabling some apps with "Disable" script, and restore with "Enable" script. 
Take note that I guessed the app package name in the script since I have no way to test GKUI script. Proceed at your own risk.
Let me know if you see any abnormalities. 

[GKUIOptimizationScript.zip](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/files/11690044/GKUIOptimizationScript.zip)

**Comment by Nicchua89** [comment]
> Sorry for my super late response. Try these scripts.
> 
> You may optimize by disabling some apps with "Disable" script, and restore with "Enable" script. Take note that I guessed the app package name in the script since I have no way to test GKUI script. Proceed at your own risk. Let me know if you see any abnormalities.
> 
> [GKUIOptimizationScript.zip](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/files/11690044/GKUIOptimizationScript.zip)

Awwww! Thanks for your script! Will try it these few days! Btw installation just like atlas step right?

**Comment by xeon1989** [comment]
Yes, just cucuk dan main. 
place the files in FAT32 formatted USB, plug and wait for the sign (something like Wireless charging should pops up).
No restart needed.

**Comment by ky960310** [comment]
Hi Xeon. I already tested the gkui optimization script. It's working on the gkui system. Bravo and thanks a million! 

By the way, i think you put the script to the wrong folder. The disable script is inside the enable folder but the reset disable ( back to original ) script you put in the disable folder.

**Comment by xeon1989** [comment]
Hi KY, thanks for letting me know.
It has been corrected.

[GKUIOptimizationScript.zip](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/files/11863895/GKUIOptimizationScript.zip)

**Comment by Jianlinooi** [comment]
> Hi KY, thanks for letting me know. It has been corrected.
> 
> [GKUIOptimizationScript.zip](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/files/11863895/GKUIOptimizationScript.zip)

hi to disable the app script just use the disable folder right? for reset back to normal is enable folder?

**Comment by xeon1989** [comment]
yes

**Comment by Nicchua89** [comment]
Yoo 🤘 Chris ! I just tested the optimization! The result is awesome!! Hu no more lag Waze and Google got better respond, autokit ( wireless android auto) no more lag ! Plus I got try to install latest car launcher free edition, all respond pretty good! I think u may release the optimization on public jor 😂😂

**Comment by Nicchua89** [comment]
Why I need to install car launcher because once done the optimization, the launcher interface will become empty, the proton ori widgets just left members info and clear ram can show. I think better to replace with car launcher 😂

**Comment by cph138** [comment]
Help.. My proton map unable to launch aftr i used reenable script..
