### ISSUE TITLE
Custom Uninstall App not working

### ISSUE THREAD

**Issue by RadenAmzar** [xeon1989/Proton-X50-APK-Installer-ATLAS#39]
I try to uninstall custom app but the script seems not working. when usb plug in, nothing happened( not going to wireless charging screen). Do i need to edit and insert custom app name in the script? Thank you.

**Comment by xeon1989** [comment]
Hi, I assume that you followed this guide for custom app installation?
https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/blob/main/Install_Your_Own_Apps.md
It seems the script not even running.
You do not need to change the uninstallation script, just copy and paste.
Make sure you have "hutroops.*" prefix in folder name.

**Comment by RadenAmzar** [comment]
yes. i followed the steps. do i need to include the “app” folder together with uninstall script? or only script file when uninstalling?

**Comment by xeon1989** [comment]
> 

There is no "app" folder in uninstallation script.
You can only have one script at a time, which means you need to delete all files before pasting content of uninstallation zip file onto USB drive.

For the moment, the uninstallation script removes all 3rd party apps. 
Treat it as the script to "reset" your HU to default state.

**Comment by RadenAmzar** [comment]
I see. Understood. Seems like i need to found a way how to uninstall specific app only.

Thank you for the quick response.

**Comment by RadenAmzar** [comment]
Folder: hutroops.org.videolan.vlc

Package: org.videolan.vlc.apk

**Comment by xeon1989** [comment]
[RadenAmzar.zip](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/files/11653222/RadenAmzar.zip)
Try this.
As usual, make sure USB drive in FAT32.
Paste the content in root directory. 

If it's still not working, probably your IHU has been updated either to version 617v2 or later...

**Comment by RadenAmzar** [comment]
Hi, i just tried the script. It works. Thank you!

**Comment by xeon1989** [comment]
Unfortunately it's part of the OS where any changes in System app require optimizing the app. Probably for Dalvik cache.
I do not have a way to skip / speed it up.
If anyone knows the way to do so, feel free to let me know so I could include that.
