### ISSUE TITLE
Adding application

### ISSUE THREAD

**Issue by Ap0k4L1p5** [xeon1989/Proton-X50-APK-Installer-ATLAS#4]
Hi Xeon, i've looked into your bash script and i found there are 2 similar scripts inside. If i want to add other application inside, do i need to modify both script? Please advise. Thank you.

**Comment by andersonkoh96** [comment]
I believe they are 617 and 618.

**Comment by xeon1989** [comment]
Hi, you can't add application by editing the content of shell script.

**Comment by Ap0k4L1p5** [comment]
Thanks for clarification xeon, is there any other way to add application as of now?

**Comment by xeon1989** [comment]
Sorry but as it is not possible to add other apps with current version of script at the moment.

**Comment by AreLangKuzee** [comment]
hello there. can u adding file manager like "es file manager" to IHU atlas 617/618....
thank you for sharing.. i support u ...

**Comment by xeon1989** [comment]
> 

Hi, why do you need File Manager? Unlike the same in GKUI, installation via FIle Manager no longe works.

**Comment by xeon1989** [comment]
> Hi, why do you need File Manager? Unlike the same in GKUI, installation via FIle Manager no longe works.



> hello there. can u adding file manager like "es file manager" to IHU atlas 617/618.... thank you for sharing.. i support u ...



> hello there. can u adding file manager like "es file manager" to IHU atlas 617/618.... thank you for sharing.. i support u ...

Hi, why do you need File Manager? Unlike the same in GKUI, installation via FIle Manager no longe works.

**Comment by AreLangKuzee** [comment]
> > hello there. can u adding file manager like "es file manager" to IHU atlas 617/618.... thank you for sharing.. i support u ...
> 
> Hi, why do you need File Manager? Unlike the same in GKUI, installation via FIle Manager no longe works.

ooo. i see... the reason is... if u can add file manager. next time i can install more apk on usb drive like AIMP.APK, MX PLAYER.APK, & NEWPIPE.APK on my GKUI like before.. and now MYIHU has upgraded to ATLAS 618... more comfirtable to play music on this AIMP.APK on usb drive.. actually better than media usb player.. VLC PLAYER is ok with that.. but its difficult to choose folder sometime... IF U CAN HELP ME.. very-very appriciated...

**Comment by xeon1989** [comment]
@AreLangKuzee thanks for sharing your feedback. File explorer is not included in this release, but we'll consider the feasibility in next release.
