### ISSUE TITLE
android ai box

### ISSUE THREAD

**Issue by Jamesryan1027** [xeon1989/Proton-X50-APK-Installer-ATLAS#40]
hi. may i know android ai box can useing in X50?

**Comment by xeon1989** [comment]
Hi, I have no idea if it can be supported since Android AI box require natively supported Carplay.

**Comment by Jamesryan1027** [comment]
Do you have any solution? Because my friend got buy this gift for me from
Taiwan. So see if you have any idea to help? Thx a lot man


Chris ***@***.***> 於 2023年6月8日 週四 上午6:50 寫道：

**Comment by Jamesryan1027** [comment]
Ok. Thx man. 😁

Chris ***@***.***> 於 2023年6月8日 週四 下午11:03 寫道：
