### ISSUE TITLE
Unable to run scrip 

### ISSUE THREAD

**Issue by Bobblies** [xeon1989/Proton-X50-APK-Installer-ATLAS#41]
Hi, there was OTA update recently and now the installed app is gonna and I'm unable to run the scrip

**Comment by halim273** [comment]
Hi Xeon, I came across this interesting YouTube video about displaying car battery voltage on a Pumpkin Android head unit (https://www.youtube.com/watch?v=vzw0UbaMI0g). It got me thinking, is there a way to achieve the same functionality on the Proton X50 Atlas IHU?

**Comment by xeon1989** [comment]
@halim273 I do not think it came with stock IHU. 
Your next best bet would be via wireless OBD2 reader, but I'm not sure either if we could connect the BT in stock IHU like what we do with our phone. 
Please give it a try and share us the outcome.

**Comment by Bobblies** [comment]
Hi Xenon , did as your advice , manage to rerun the scrip and install those apps but it seems that I am unable to log into my google account for the YouTube music.

**Comment by xeon1989** [comment]
Hi, have you tried both Google login and Huawei login?
Personally Huawei login works for me.
