### ISSUE TITLE
Stuck at Android Optimize App.

### ISSUE THREAD

**Issue by radio841** [xeon1989/Proton-X50-APK-Installer-ATLAS#44]
Anything can be done if stuck at android optimize app? My IHU will reload after 25 of 54. Then reboot, and reload again at 40 something of 83. The thing is i use the script to delete bootanimation and tried to replace it with other video. 

should be 
```
rm -rf /system/media/bootanimation.mp4
cp /mnt/media_rw/udisk1/bootanimation.mp4 /system/media/
chmod 644 /system/media/bootanimation.mp4
```

instead of 
`rm -rf /system/media/bootanimation.mp4
cp /mnt/udisk2/bootanimation.mp4 /system/media/
chmod 644 /system/media/bootanimation.mp4`

help. now cannot go in. always android optimizing.

**Comment by xeon1989** [comment]
Hi, for Proton's IHU we do not have anything mounted behind udisk2. 
In your case, copying and set permission should ends up with error. 

Your next best bet is to hope it's reading script while showing "Optimizing..." message.
Did you keep the backup of bootanimation.mp4 ? 
Else you can download the copy I attached in this reply. 
"Paste" it back by:

> cp /mnt/media_rw/udisk1/bootanimation.mp4 /system/media/ && chmod 644 /system/media/bootanimation.mp4

Take note that it is very, very risky to "delete and copy file", especially system file. 
Please use cp to replace the file. If it fails, at least it's not removing files. 

https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/17538895/f7da1b0b-9f40-41a8-b802-2c99bcc3ede3

**Comment by radio841** [comment]
tq . all done

**Comment by xeon1989** [comment]
Hi, mind to update if it works now?
What you did to fix it?

**Comment by radio841** [comment]
> Hi, mind to update if it works now? What you did to fix it?

sorry i wrongly mark as solved. all i did was change to 
```
cp /mnt/media_rw/udisk1/bootanimation.mp4 /system/media/
chmod 644 /system/media/bootanimation.mp4
```
and yes, the script miraculously reading by the time of optimizing app. lucky for me. 
and i managed to replaced the bootanimation. 

btw, can i reach u by any media social ? telegram etc. hehe. https://t.me/baihaqimahzan

**Comment by radio841** [comment]
https://www.facebook.com/RaDiO.KiLLeR/videos/1030510015024375?idorvanity=770920149929041

here is preview of the bootanimation. wrong resolution. need to resize again.
