### ISSUE TITLE
CarlinKit CarPlay Ai Box Android 12 Plus - won't let me change the name of the car!

### ISSUE THREAD

**Issue by ANJOdePORTUGAL** [xeon1989/Proton-X50-APK-Installer-ATLAS#45]
Who can assist me, please, with the following issue?

I want to change the name displayed on the car screen (see the screenhot), like I do with my iPhone Bluetooth connection, but I am not able to do it, so far. 
The system won't let me change the name of the car!

I changed the Carlink Bluetooth device name, but nothing happened, I mean, the renamed Bluetooth is not being displayed.

**AutoKit-Tbox Plus version** : X9-SC138-4 A12 2023-05-29 .

![Carlink_name](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/135832285/f2a4da01-4452-4a34-a05d-603a8bda0816)

I can donate if necessary. I don´t want you waste free time on me :)
Thank you.

**Comment by xeon1989** [comment]
Hi, unfortunately I do not have a way to replicate. Sorry but I could not further support this case. :(
