### ISSUE TITLE
Trying to make keyremap work. 

### ISSUE THREAD

**Issue by radio841** [xeon1989/Proton-X50-APK-Installer-ATLAS#46]
Hi, im sorry to disturb your time. 

is it 
```
echo "========Enable keyremap======="
pm grant flar2.homebutton android.permission.WRITE_SECURE_SETTINGS
```
or 
```
echo "========Enable keyremap======="
pm grant hutroops.flar2.homebutton android.permission.WRITE_SECURE_SETTINGS
```
im not that good in programming. hehe

**Comment by xeon1989** [comment]
Former one, since that's the package name. 
I tried the same but with no good result. 
Please let me know if you got it to work. :)

**Comment by xeon1989** [comment]
My gut feeling tolds me there might be something running that listening to the KeyEvent, which render other apps not able to listen to KeyEvent. 
It might be Media app (com.malaysia.media) or Media Widget (com.malaysia.audiowidget).
I did not further check on that due to time. 

Hope this helps.

**Comment by amiraizat124** [comment]
> My gut feeling tolds me there might be something running that listening to the KeyEvent, which render other apps not able to listen to KeyEvent.
> It might be Media app (com.malaysia.media) or Media Widget (com.malaysia.audiowidget).
> I did not further check on that due to time.

![image](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/44428060/aa177ed7-3be4-48ed-8a5c-926333851a88)

This how to disable the apps? I want to try it

com.malaysia.media
com.malaysia.audiowidget

what this apps for?

**Comment by xeon1989** [comment]
yes, pm disable <package_name> is the way to disable app.
Take note you might have permission issue. 

That 2 apps I mentioned, former one for Music app, latter one for "widget" in Home screen.

**Comment by radio841** [comment]
nvm, cannot get to work. should have one discussion group to break the code. haha. tq for your time.
