### ISSUE TITLE
USB Option after entering in engineering mode is disabled

### ISSUE THREAD

**Issue by kamichettysiva** [xeon1989/Proton-X50-APK-Installer-ATLAS#47]
![image](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/28698677/c96a0e58-22f8-4e60-ba4e-ba3886cbd45e)

Can you please advise if flashing out to 617 is disabled with latest OTA update SWOSXRA0413H5170.00644

**Comment by xeon1989** [comment]
No, it's not disabled.
Check if you have correct files in USB, make sure you only unzip once after downloaded.
It should be a .zip file.

**Comment by kamichettysiva** [comment]
Thank you Xeon .. it worked!
