### ISSUE TITLE
Google Assistant not working

### ISSUE THREAD

**Issue by Sea-Abbrevtions** [xeon1989/Proton-X50-APK-Installer-ATLAS#48]
Hi xeon, I would like to thank you for providing your script to download apps on x50, However, when I'm in android auto my google assistant doesn't seem to work. It responds to my 'Hey Google' prompt, but it doesn't further respond to anything that I say afterwards. It just sort of hangs and closes. I use a Samsung s21 ultra with android 13

**Comment by amiraizat124** [comment]
You are using Carlink Kit or HUR?

**Comment by Sea-Abbrevtions** [comment]
I'm using HUR

**Comment by amiraizat124** [comment]
![20230715_072818](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/44428060/a9cf3f7c-1640-4f47-a390-4a05ca5d0a05)
U need to set microphone input source to Mic

**Comment by Sea-Abbrevtions** [comment]
Thnk you so much. FInally fixed the issue.
