### ISSUE TITLE
No apps showed up after the script ran

### ISSUE THREAD

**Issue by fevernova90** [xeon1989/Proton-X50-APK-Installer-ATLAS#5]
Performed the steps as per README.

After the IHU restarted, those new sideloaded apps didn't show up in the Dashboard.

Not sure if this is related to I'm using MacOS to unzip and copy the shell scripts and APKs folders.

Using the following OS to extract files:
- MacOS Ventura 13.2.1 (22D68)
- Formatted USB drive using MacOS built-in Disk Utility to FAT32 (Fastest mode option in security settings)
- 32GB USB Drive

My IHU is running `ATLAS 617`.

This is the logs from the USB drive ...
[outputInstall_1676363106.txt](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/files/10730713/outputInstall_1676363106.txt)

From the logs there's an error to run the `MAIN` intent (which I believe to just show the main screen, correct me if I'm wrong). Also the copies and permissions commands looks okay (no error output).

I don't have Windows machine right now to try on, and will do once I get my hands on one.

**Comment by xeon1989** [comment]
Hi, based on the content of logs, installation succeeded.
Could you manually reboot and check again?
Maybe a silly suggestion, but try to swipe left few more times and make sure apps didnt "hide" in additionally created page.

**Comment by fevernova90** [comment]
@xeon1989 I will run the script again, check new pages, reboot and will let you know as I already run your uninstaller right after.

And yeah, hidden apps in new page might be the case too, too rush doing it.

Silly question from me too, can we reboot the IHU manually without turning off the engine and lock car?

**Comment by xeon1989** [comment]
Hi, yes you can.
Hold the power button for 15secs or so

**Comment by fevernova90** [comment]
Found the culprit!

Apparently MacOS places additional files on top of your files, prefixed with `._`, e.g: `foo.apk` will be accompanied by `._foo.apk`.

The reason for this is that FAT32 cannot store the extra metadata that MacOS "required", and they store it in an extra hidden dotfiles.

I found this additional files while looking at my log output earlier.

<img width="654" alt="Screenshot 2023-02-15 at 12 03 35 AM" src="https://user-images.githubusercontent.com/34376497/218791804-7f8b4e6d-e931-4495-acb4-cb0e905a0014.png">


The weird part is that Android doesn't like that extra dotfiles and probably skip the APK during startup.

I managed to get mine working by removing the dotfiles using macOS native library `dot_clean -m path-to-usb-volume` before removing the USB drive, not sure if there's linux equivalent to it but my guess is using something like `find . -iname '._*' -delete` in your shell script might do it.

I think the solutions we can give people when they're using macOS is one of these:

1. Run `dot_clean -m path-to-volume` in macOS terminal before removing the USB drive.
2. Or, include the `find . -iname '._*' -delete` somewhere in your shell script.

I haven't tested the no 2 as a bit scared to bluntly run `delete` or `rm -rf` command, might accidentally delete other files and broke things, LOL.

And thank you @xeon1989 for your kindness and work to provide this whole sideload solution to us for free. Will buy you some coffee. Cheers.

**Comment by xeon1989** [comment]
Hi, I took another look after reading your comment, indeed!
In fact, Android hates 2 apk in a single directory.
Thanks for sharing your finding! Would you mind for me to link your finding in the README?
![Uploading IMG_20230215_080549.png…]()

**Comment by fevernova90** [comment]
@xeon1989 go ahead!

**Comment by huihongteh** [comment]
Hi, I tried the above commend (method 1) before removing my USB from Macbook. After plug in to ALTAS, it finished the installation process, I couldn't find the app from the device.

Can anyone please help on this? Thanks. 
[outputInstall_1676938282.txt](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/files/10820921/outputInstall_1676938282.txt)

**Comment by xeon1989** [comment]
> Hi, I tried the above commend (method 1) before removing my USB from Macbook. After plug in to ALTAS, it finished the installation process, I couldn't find the app from the device.
> 
> Do i need to run the uninstall script before redo everything again?
> 
> Can anyone please help on this? Thanks.
> 
> [outputInstall_1676938282.txt](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/files/10820921/outputInstall_1676938282.txt)

Based on the log, i still see dot underscore files.
Please check if the file really cleaned up after following method 1.
Please Uninstall and install again, make sure no dot underscore file while preparing the installation.

**Comment by fevernova90** [comment]
@huihongteh yeah, from the logs, there's still `._` files being copied over to IHU.

Make sure that the USB volume path is correct when running `dot_clean -m path-to-volume`. In MacOS, your USB drive should be located in `/Volumes/`, e.g: `/Volumes/My_USB`.

Also for confirmation before removing the USB drive, you can traverse the USB drive using terminal to check if there's still dotfiles by `cd` into the volume and its folders (especially APKs subfolders) and running `ls -al` to list all hidden files.
