### ISSUE TITLE
Must Manually Open Media App for Bluetooth Audio activation

### ISSUE THREAD

**Issue by kanasite** [xeon1989/Proton-X50-APK-Installer-ATLAS#51]
@xeon1989 Hi Chris, currently it seems like despite the bluetooth is connected to the IHU, it's still required to "manually" trigger once for the Bluetooth Audio channel switching by manually opening the Media app. Is there any workaround or what kind of command we can send to trigger the audio channel switching automatically?

**Comment by xeon1989** [comment]
for my method, I launch Media app first, then plug USB cable in so that Android Auto would auto launched. 
With this extra steps, Audio switching should works once Android Auto launched.

**Comment by xeon1989** [comment]
@kanasite thanks for further clarifying. 
I myself not a CarPlay user, this would require others to comment. 
I will reopen this Issue and open for others to comment.

**Comment by kanasite** [comment]
> @kanasite thanks for further clarifying.
> I myself not a CarPlay user, this would require others to comment.
> I will reopen this Issue and open for others to comment.

@xeon1989 thanks, Just curious if you don't launch "Media" app after boot-ing your car, and connect your phone's bluetooth to the car (and audio output on your phone is bluetooth), and play music on your phone, will the car speaker plays the music?

**Comment by xeon1989** [comment]
For my case it won't auto play too.
Perhaps can install some other apps to auto start Media app during startup?
