### ISSUE TITLE
Support for latest Atlas version

### ISSUE THREAD

**Issue by valehelle** [xeon1989/Proton-X50-APK-Installer-ATLAS#52]
Anyone working to support the latest Atlas version? 

Is there anything I can help or can someone point me to the right direction?

Since the script rely on specific path to run. My guess is that the new Atlas version change the path?

**Comment by xeon1989** [comment]
New ATLAS removes the code specifically to stops reading content in USB drive.
There is no active development from me since it works for my 617.
