### ISSUE TITLE
Install and Uninstall script for Newpipe only

### ISSUE THREAD

**Issue by ky960310** [xeon1989/Proton-X50-APK-Installer-ATLAS#54]
Hello good day Xeon. Can create the script for install and uninstall Newpipe only? Since Newipe cannot manual update in Atlas, if Newpipe have update version I can uninstall the old version and install the new version for my members easily without erase everything and have to reinstall back them again.

Thanks a million 🫡❤️

**Comment by xeon1989** [comment]
Hi Khay Yin, could you please try to remove all other apps in installation scripts and keep only the folder for newpipe?
Make sure you follow steps 6-11 in "install your own app" guide to replace it with latest newpipe apk and libs.
Let me know if it the updateworks by replacing the app without uninstalling it first.

**Comment by ky960310** [comment]
> Hi Khay Yin, could you please try to remove all other apps in installation scripts and keep only the folder for newpipe?
> 
> Make sure you follow steps 6-11 in "install your own app" guide to replace it with latest newpipe apk and libs.
> 
> Let me know if it the updateworks by replacing the app without uninstalling it first.  

Hi Xeon, for the first time, i try to install Newpipe without uninstalling it first. I have follow all your guide properly. After reboot, it has no any response when I press Newpipe. Same as Autokit app as well, that's why last time you created a script just for uninstall and reinstall back the Autokit only.

**Comment by ky960310** [comment]
> Hi Khay Yin, could you please try to remove all other apps in installation scripts and keep only the folder for newpipe?
> 
> Make sure you follow steps 6-11 in "install your own app" guide to replace it with latest newpipe apk and libs.
> 
> Let me know if it the updateworks by replacing the app without uninstalling it first.  

Hi Xeon, for the first time, i try to install Newpipe without uninstalling it first. I have follow all your guide properly. After reboot, it has no any response when I press Newpipe. Same as Autokit app as well, that's why last time you created a script just for uninstall and reinstall back the Autokit only.

**Comment by xeon1989** [comment]
Ok, understood. Give me some time, let me try to combine the installation / uninstallation process in a single package.

**Comment by ky960310** [comment]
> Ok, understood. Give me some time, let me try to combine the installation / uninstallation process in a single package. 

Thanks xeon 🫡

**Comment by xeon1989** [comment]
Hi Khay Yin, try this and let me know if it works. 

Just extract and place all files in USB, then plug it in USB port.
IHU should reboot once after showing Android native Settings app briefly.
Keep it plug in until you see it reboot again for second time. (it should reboot twice in total)

Once IHU stopped rebooting, check if the newpipe updated. 

I have included latest (as of 31-Aug-23) NewPipe legacy app. 
Just follow the steps 1-2 in [Install your own apps](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/blob/main/Install_Your_Own_Apps.md) guide to replace and rename NewPipe apk file.

**Comment by ky960310** [comment]
> Hi Khay Yin, try this and let me know if it works. 
> 
> 
> 
> Just extract and place all files in USB, then plug it in USB port.
> 
> IHU should reboot once after showing Android native Settings app briefly.
> 
> Keep it plug in until you see it reboot again for second time. (it should reboot twice in total)
> 
> 
> 
> Once IHU stopped rebooting, check if the newpipe updated. 
> 
> 
> 
> I have included latest (as of 31-Aug-23) NewPipe legacy app. 
> 
> Just follow the steps 1-2 in [Install your own apps](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/blob/main/Install_Your_Own_Apps.md) guide to replace and rename NewPipe apk file. 

Thanks xeon! I'll try it asap! Thank you so much!

**Comment by ky960310** [comment]
> Hi Khay Yin, try this and let me know if it works. 
> 
> 
> 
> Just extract and place all files in USB, then plug it in USB port.
> 
> IHU should reboot once after showing Android native Settings app briefly.
> 
> Keep it plug in until you see it reboot again for second time. (it should reboot twice in total)
> 
> 
> 
> Once IHU stopped rebooting, check if the newpipe updated. 
> 
> 
> 
> I have included latest (as of 31-Aug-23) NewPipe legacy app. 
> 
> Just follow the steps 1-2 in [Install your own apps](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/blob/main/Install_Your_Own_Apps.md) guide to replace and rename NewPipe apk file. 

So I just need to download the latest script, extract to usb and plug into the usb port then it will uninstall and reinstall the latest Newpipe automatically?

**Comment by ky960310** [comment]
Hello @xeon1989 , here's the update after I tried to update Newpipe with your tutorial.

It's work! Download your latest installation script and the latest newpipe apk, rename the latest newpipe apk with the same name as the old one, paste into the hutroops newpipe folder, then with the script folder all together copy into the pendrive and plug into the car.

The proton start up screen will show up 2 times, after that have to wait it to load finish. 

Thank you so much Xeon!
