### ISSUE TITLE
HU wont automatically connect to Bluetooth device

### ISSUE THREAD

**Issue by ky0112** [xeon1989/Proton-X50-APK-Installer-ATLAS#56]
Notice that after the car startup the HU wont connect to phone Bluetooth. You need manually turn off and turn on the Bluetooth on HU so that phone will automatically connect to the HU.
Is it possible to write a cron script to automatically off the Bluetooth and then on back Bluetooth during the HU startup(start car)?
Thanks

**Comment by xeon1989** [comment]
Hi, for me I do not experience issue with Bluetooth auto connection.
Nevertheless, this is out of the scope of this script. 
Feel free to research on your own and share public your finding. 🙂
