### ISSUE TITLE
YT Music

### ISSUE THREAD

**Issue by vymal** [xeon1989/Proton-X50-APK-Installer-ATLAS#57]
YT Music always fails to login to Google Account. Connection issues is this known?

**Comment by xeon1989** [comment]
Do you mean Vanced Music? I believe it no longer works in Android Lollipop. Try Newpipe.

**Comment by vymal** [comment]
> Do you mean Vanced Music? I believe it no longer works in Android Lollipop. Try Newpipe.

Could you guide me to the  NewPipe. Thanks

**Comment by xeon1989** [comment]
The installation script posted in README.md included NewPipe. 
It might be outdated, you just need to download it from [NewPipe website](https://f-droid.org/repo/org.schabi.newpipelegacy_120.apk), rename and replace it in new pipe folder under /apps. 

I am quite occupied lately, will update apps in script pack when I got myself some time.
