### ISSUE TITLE
YouTube vanced and YouTube music vanced

### ISSUE THREAD

**Issue by jctang1028** [xeon1989/Proton-X50-APK-Installer-ATLAS#58]
Hi, good day to all
Since some people face unable to use YouTube Vanced or YouTube Music vanced 
I’m here to share my experience when use both apps. 
Actually I have subscribing “YouTube premium” so I still can use both apps flawlessly 
So if you are YouTube premium subscribers you still can use both apps by log in your own google account
But if you are not YouTube premium subscriber, newpipe is preferred to you
Hope this information can help who needs

**Comment by xeon1989** [comment]
IMO vanced still far better than all alternatives due to its native support in wide screen devices (tablet mode). 
Although the navigation is challenging, Smart Tube is still a good option.
