### ISSUE TITLE
Curious Question here

### ISSUE THREAD

**Issue by Micansaaron** [xeon1989/Proton-X50-APK-Installer-ATLAS#59]
Ori IHU proton maps nagivation can display nagivate on meter. Any chances or possibility to use waze overwrite the proton maps scripts and nagivation able to display on meter ?
Thanks!!

![image](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/125079850/3fe658e0-7dd2-41d2-96c8-049ed1bf34b2)

**Comment by xeon1989** [comment]
Hi, it's out of my expertise to adapt / implement such features.
I am willing to provide my support if anyone would like to do so.

**Comment by Micansaaron** [comment]
Hi @xeon1989 based on your knowledge, there’s chances to happen?

**Comment by xeon1989** [comment]
@Micansaaron maybe. I saw Philipine group did that for their Coolray, but did not further study the details

**Comment by Micansaaron** [comment]
@xeon1989 thanks for the feedback and your effort. Appreciated 🤡
