### ISSUE TITLE
iOS CarPlay notification 

### ISSUE THREAD

**Issue by Micansaaron** [xeon1989/Proton-X50-APK-Installer-ATLAS#62]
Hi there Xeon, are there everyone the same that when CarPlay connected, our phone will not show any notification when it is lock/unlock. Notification will only display on CarPlay screen. There is impossible to display notification on both devices ? (Phone screen and CarPlay screen)

**Comment by xeon1989** [comment]
Hi, as I am not CarPlay user myself, I do not have the knowledge to comment on the behavior. 
I think it would be the best to bring this question to Carlinkit as they are the author of Autokit app and Carlinkit dongle.

**Comment by Micansaaron** [comment]
I have connect with Apple regarding this issue. But they said everything is working fine on their IOS even troubleshooting have been done. So most probably is carlinkit firmware issue 😅
