### ISSUE TITLE
Uninstall specific app only

### ISSUE THREAD

**Issue by ky960310** [xeon1989/Proton-X50-APK-Installer-ATLAS#65]
Hi, Xeon! 

I have a request. I'm not sure if you're willing to teach me how to uninstall specific app? I have used the Note software to open your installation and uninstall script files, as well as the script file you made before that only uninstall Autokit.

I have also browsed the forum from prsyahmi/proton firmware and tried to explore their provided Cyber Chef " recipe " but I have no idea how to proceed.

I can't figure out why there are two .sh files in your "b832bcxxxx" folder, but when I open them with Note, I find that the contents are exactly the same. I just can't understand what I'm missing.

I hope you can guide me so that I can provide more convenient and free help to fellow car enthusiasts. This way, I won't have to help them by deleting all the software, reinstalling, and then setting up again.

Thank you!

**Comment by ky960310** [comment]
I also copied the contents of your script to ChatGPT and asked ChatGPT to help me write a script to delete a specific app. Then I copied it to Cyber Chef.

In the output, I saw the "xxxxxx.sh" file, but I can't figure out how to create the other script file. Why I saw your scripts have the same content but different names?

**Comment by ky960310** [comment]
Hey @xeon1989 

Thank you for your patient answers and guidance. Thank you for your selfless sharing! I'm very grateful for your efforts! I'll try & error again, after reading your explanations, I feel that it won't defeat me. Thank's again!

May all the light at the traffic turn Green for you ✌🏻🫰🏻

**Comment by xeon1989** [comment]
@ky960310 Hi Kai Yin, in case you are still working on this topic, I have made a more comprehensive guide in [this reply](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/issues/68#issuecomment-1863760449).
Feel free to check out if it helps.
