### ISSUE TITLE
couldnt connect to IHU internet to apps

### ISSUE THREAD

**Issue by misterweird** [xeon1989/Proton-X50-APK-Installer-ATLAS#66]
i have remaining data in my IHU connectivity data. but i couldnt get to use to data for the apps.

**Comment by ky960310** [comment]
> i have remaining data in my IHU connectivity data. but i couldnt get to use to data for the apps. 

Try go to member center app, after that log out and re-login back.

**Comment by misterweird** [comment]
it works. Actually i factory reset the ihu and re-login.
