### ISSUE TITLE
unable to login in smart tube and syok app unable to play live radio

### ISSUE THREAD

**Issue by misterweird** [xeon1989/Proton-X50-APK-Installer-ATLAS#67]
on the page where we get the code to sign in smart tube...it remains retrieving the code. how can i solve this problem? and  syok broadcast is usable but live radio is not working.

**Comment by xeon1989** [comment]
Hi, please check with other smart tube user or author of smart tube app to narrow down the root cause.

**Comment by bizdatech** [comment]
Smartube u need the custom script , 

if using the full script wont work. 

syok new version no longer working.

**Comment by bizdatech** [comment]
> Hi, please check with other smart tube user or author of smart tube app to narrow down the root cause.

Hi there, 

i check your reinstall script for the newpipe. 

how it works? i download all the folder put into the usb root. 

not running, then i just put only one folder and rename delete the reinstall font. 

it runs, but the apps still there.

**Comment by xeon1989** [comment]
Hi, what do you mean by not running? 
Could you please share the log files in your USB?
It should be the file with name "Output_*".

**Comment by bizdatech** [comment]
Hi Xeon,

after u request the output. 

i redo again because i deleted the files. 

here the report. 

your uninstall folder. = one of the filename u put sh.sh <--- have two "SH" .

so i have rename to .SH only and it works. 

i having this newpipe issues that i downloaded is the latest newpipe. v26

Their file name change into this filename com.newpipe.protube 

not sure newpipe have shutdown their service or what i dunno. cuz the app itself say they r under updating the app but 3 days now still same warning.  that is why i came into your github, saw u have this updates. 

Thx u sir.

**Comment by bizdatech** [comment]
if i want to uninstall the other apk.

is it i change the apk name follow delete example

(filename).com.spotifylegacy
(filename).com.spotify

is it like that?

**Comment by xeon1989** [comment]
> your uninstall folder. = one of the filename u put sh.sh <--- have two "SH" .
> 
> so i have rename to .SH only and it works.
> 

Ok, now I got it.
It only affects Executive script so it went under my radar.
Thanks for reporting, it has been fixed.


> if i want to uninstall the other apk.
> 
> is it i change the apk name follow delete example
> 
> (filename).com.spotifylegacy (filename).com.spotify
> 
> is it like that?

Yes, just change the folder and file name according to the package name. 

> after change app name from the script that i wan to uninstall the newpipe protube.
> 
> the script seems like not executes... i keep trying the workaround seems not working.
> 
> so maybe will u help to put up a script that we can uninstall the particular app?

You need to change the script name as the script name changes according to script content.
See https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/issues/65#issuecomment-1837675763 in another issue for the creation of the uninstallation script, especially Q2 about generating script name respectively. 

Unfortunately for now I do not have the resources to create separate script to selectively uninstall an app. 💀
Feel free to contribute if that's okay for you.
