### ISSUE TITLE
Android auto setting page keep popping up 

### ISSUE THREAD

**Issue by cjjong82** [xeon1989/Proton-X50-APK-Installer-ATLAS#68]
Hi, been experiencing Android auto setting page pop up by itself a lot lately. 

Any idea how to stop it from happening?

or Can i uninstall the Android Auto app for carlinkit for good?

Further more after second time auto pop up and app exited, FM radio will stop playing too. 

Pleading master sifus for a solution on this issue. Thank you 🙏 

![IMG_0167](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/149695453/dcc48611-5f21-4859-bec5-4476c4d9683e)

**Comment by xeon1989** [comment]
Hi, if you don't need Anndroid Auto (Headunit Reloaded), you may uninstall it with this script.

[uninstall headunitreloaded.zip](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/files/13696234/uninstall.headunitreloaded.zip)

**Comment by aliffmufc** [comment]
Hi xeon. Is this uninstaller will remove all other apps? Can i just uninstall unwanted single app rather than to uninstall whole apps? Thanks

**Comment by xeon1989** [comment]
@aliffmufc no, that only uninstalls Android Auto.
For uninstallation of specific apps, it has been mentioned in this Issue.

https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/issues/65

**Comment by aliffmufc** [comment]
Sorry to ask further. So to uninstall specific app, i just input folder name at red line as per attached photos? Thanks for your guide
![IMG_6888](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/136944546/166ad58b-24c2-4949-9b57-3e1f24697e7b)

**Comment by xeon1989** [comment]
@aliffmufc no issue asking further question, I'm happy to assist. 
Based on your picture it seems you have downloaded the Uninstallation Script from the README.md page.

For simplicity you may start with this template.

1. Unzip above zip file and locate template.sh under "b832bc61472727635baffcf25dd28e9f239273e2" folder, right click and open with Notepad.
![image](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/17538895/04fcd2fe-b7c1-42c0-a113-9202b7abefd9)

2. Change Package Name in line 15 and 16. You may refer to APKPure in the URL of the app page.
For eg: Headunit Reloaded (Android Auto) = gb.xxy.hr (https://apkpure.com/headunit-reloaded-emulator-hur/gb.xxy.hr)
![image](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/17538895/033a5579-e068-4ef2-b555-ccf8d9c5fe11)

3. If you have more apps to uninstall, duplicates line 15 and 16 with Package Name of the app. Else skip this step.
![image](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/17538895/327a7504-605a-4753-89bd-b43319899663)

4. Save the file.

5. Generate the file name in CyberChef by uploading template.sh. For [Standard/Executive use this link](https://gchq.github.io/CyberChef/#recipe=MD5()Find_/_Replace(%7B'option':'Regex','string':'$'%7D,'sx11ra_ds_2wk',false,false,false,false)MD5()Find_/_Replace(%7B'option':'Regex','string':'$'%7D,'Super%20Savior%20Hero',false,false,false,false)MD5()Find_/_Replace(%7B'option':'Regex','string':'$'%7D,'.sh',false,false,false,false)&input=VVBMT0FEIEZJTEUgSEVSRQ). For [Premium/Flagship use this link](https://gchq.github.io/CyberChef/#recipe=MD5()Find_/_Replace(%7B'option':'Regex','string':'$'%7D,'sx11ra_qj_2wk',false,false,false,false)MD5()Find_/_Replace(%7B'option':'Regex','string':'$'%7D,'Super%20Savior%20Hero',false,false,false,false)MD5()Find_/_Replace(%7B'option':'Regex','string':'$'%7D,'.sh',false,false,false,false)&input=VVBMT0FEIEZJTEUgSEVSRQ). 
![image](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/17538895/3a24c11f-d271-47e0-aebd-f15348029bcc)

6. Rename template.sh with the text generated in Output. 
![image](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/17538895/ba8eb693-fff9-4663-8343-2a462f611adb)
![image](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/17538895/ccabf44f-c83f-44b4-9645-d5c0821180aa)

7. Copy the b832bc... folder onto USB drive and run script as per usual. Your IHU should reboot once execution complete.

**Comment by cjjong82** [comment]
Thank you so much Chris! @xeon1989 

 Uninstalled Android Auto successfully with the provided script. 
 
The whole process took approximately 10mins mostly taken place on reloading the apps ( app optimizations on the 64 apps). 

Next is to install reinstall New Pipe 😬

**Comment by xeon1989** [comment]
@cjjong82 I have made reinstallation script to update NewPipe to version 0.25.2, it's in main page under Important Updates section. 
https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS

**Comment by cjjong82** [comment]
Yes Chris I saw that. Didn’t dare to do it one shot as in uninstalling and installing app simultaneously. Or it can be done so?

**Comment by xeon1989** [comment]
@cjjong82 it has been proven works in this issue.

https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/issues/54

**Comment by cjjong82** [comment]
Hi Chris, I’ve ran the script which took 30mins to complete the 2 reboots cycle. However didn’t see the Newpipe app. Instead, there’s an empty space shown. Do I need to download the Newpipe apk and put in the hutroops folder?
![IMG_0201](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/149695453/71bc0c2a-6385-402b-b118-0b5fcd4548eb)

**Comment by xeon1989** [comment]
Hi @cjjong82, would you mind to share the log files in USB drive?
File name should be outputUninstall_*.txt and outputInstall_*.txt.

**Comment by cjjong82** [comment]
Here you go Chris...
[outputInstall_1703131621.txt](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/files/13736913/outputInstall_1703131621.txt)
[outputUninstall_1703130776.txt](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/files/13736914/outputUninstall_1703130776.txt)

**Comment by xeon1989** [comment]
I think I know what's wrong. Will come back later tonight with a fix.

**Comment by Jamesryan1027** [comment]
hi xeon1989. may i ask you how to Rename template.sh with the text generated in Output? i already try copy and download the   .sh. but when i use notebook open file nothing txt inside. 
 ![image](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/127386272/0ee1236f-ab7c-4e8e-ad17-91d769abb1e0)1989

**Comment by xeon1989** [comment]
@cjjong82 i made the fix. Could you please give it a try?
https://drive.google.com/file/d/112xlbLuzMN0xytWAPEN6jmsa0y-YkRfQ/view?usp=sharing

**Comment by xeon1989** [comment]
@Jamesryan1027 just the usual way. 
Highlight text in Output, right click - copy. 
Then go to template,txt, right click - rename, paste the new name.
Take note that if you have file extension hidden (.sh) in your File Explorer, make sure you don't paste file extension and make it duplicate.

**Comment by Jamesryan1027** [comment]
> @Jamesryan1027就用通常的方式。 突出顯示輸出中的文本，右鍵單擊 - 複製。 然後轉到template,txt，右鍵-重新命名，貼上新名稱。 請注意，如果檔案總管中隱藏了檔案副檔名 (.sh)，請確保不要貼上檔案副檔名並使其重複。

thx bro. already got it. thx you so much.

**Comment by cjjong82** [comment]
Merry Christmas @xeon1989 !

I tried the fix you gave but still don't have the Newpipe app.

Here's the text files:
[outputInstall_1703490338.txt](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/files/13765287/outputInstall_1703490338.txt)
[outputUninstall_1703489502.txt](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/files/13765288/outputUninstall_1703489502.txt)

Do you think I can try with just the installation script for Newpipe app?

**Comment by xeon1989** [comment]
@cjjong82  for some reason the uninstaller seems failed to clean old newpipe installation.
I have made some ammendment again.
Please try this.

https://drive.google.com/file/d/112xlbLuzMN0xytWAPEN6jmsa0y-YkRfQ/view?usp=sharing

**Comment by cjjong82** [comment]
@xeon1989 Third time is a charm Chris! your code worked. Newpipe app was installed successfully. Thank you so much for your effort and time. Thank you.

**Comment by aliffmufc** [comment]
Hi xeon. In referring to your "templete" script, i have tried but not working to uninstall specific app. I noticed when open it with note, there is "gkui" word & "_done" in that script. Is that templete is used/done one & not suitable for atlas ver. Thanks.

**Comment by xeon1989** [comment]
@aliffmufc by "gkui" and "_done", are you referring to line 10 and line 24 respectively? 
Those are correct and expected. 
See echo and comment for description.

What do you mean by not working to uninstall specific app? 
Perhaps you can show me your edited script and log file so I could further advice.

**Comment by aliffmufc** [comment]
@xeon1989 
![IMG_6929](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/136944546/8f6512cd-e783-4fd8-967a-fffe953f496b)

Hi xeon. This is my uninstallation script
![IMG_6928](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/136944546/1e525681-0d99-404f-89e3-f665ea480318)
inst
![IMG_6927](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/136944546/80a3b20a-0b9e-4778-b5e2-bd8a1879b577)

**Comment by xeon1989** [comment]
You are having Premium / Flagship IHU right?
Your script looks fine so I do not see any reason it doesn't uninstall Scillarium Studio. 

It should at least execute the script and generate outputSelectiveUninstall_*.txt log file.
If you can't find this file in your USB drive, try check if you already formatted your USB drive with FAT32 file system.  


Out of topic: If you know any good IP TV app to watch Malaysia's TV station for Android TV, please let me know. I need it for my parent's TV 😅

**Comment by aliffmufc** [comment]
Hi @xeon1989 
Thanks for your reply. Nevermind, i will try it again 😊 really appreciate your guide.
Btw, ott navigator iptv is quite good bcoz its lifetime use & very cheeper (around rm7.00++). May buy its access from shopee though 😄 

Besides, I heard iptv smarters pro is better but the subscription is pricey following how many months that you choose. But ott navigator iptv is actually good enough to have 👍🏻
