### ISSUE TITLE
Duplicate of Caller Notification

### ISSUE THREAD

**Issue by sobosoboso** [xeon1989/Proton-X50-APK-Installer-ATLAS#69]
Hi

Not sure if it’s only me who faced the problem. Appreciate if anyone could share any method to fix the duplicate of caller notification - one from carplay, and one from Atlas.

I have tried disconnecting my phone from the car bluetooth, but it will also disconnect the carplay bluetooth connection. I would love to only receive call notification coming from carplay.

Looking forward for your reply.

Thanks

![IMG_2832](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/154385421/58970cc2-73c3-415e-8599-740ba7e236f8)

**Comment by xeon1989** [comment]
Hi, I believe this is expected as ATLAS OS intergrates its own notification and not natively integrated in Carplay / AA. 
It needs to be disabled in Media app of ATLAS OS. 
Despite I have not spend much time exploring this, I believe this is not possible as the Media app does not offer capability to stops the pop up.

**Comment by sobosoboso** [comment]
Thanks Chris for the clarification. 😊
