### ISSUE TITLE
Spotify issue

### ISSUE THREAD

**Issue by godsmack321** [xeon1989/Proton-X50-APK-Installer-ATLAS#7]
Unable to connect to network.
Home page constantly shows "something went wrong"
Liked songs can only play for 11 seconds and stops after.

Thanks😁

**Comment by godsmack321** [comment]
Update: 
Steering wheel control unable to select next song. 
Spotify works fine in android auto.

Thanks!

**Comment by godsmack321** [comment]
Update:
Spotify now works after clearing cache.
Steering wheel control still unable to use

Thanks 😁

**Comment by nyzam81** [comment]
i am happy as long spotify running, just press next button or create own playlist for now

**Comment by xeon1989** [comment]
Steering wheel button are not working at the moment. Am checking for solution  / workaround for the mean time.

**Comment by godsmack321** [comment]
Thank you for everything Chris

**Comment by xeon1989** [comment]
@godsmack321 FYI workaround for steering button in [this docs](SteeringButtonWorkaroundAA.md).
Not the perfect solution, but it should do the job for this moment.

**Comment by godsmack321** [comment]
hi chris, the link you provided has no attachments 
![image](https://user-images.githubusercontent.com/125517185/220323406-021f8c2b-d741-4758-9de9-6a90f270bc74.png)

**Comment by xeon1989** [comment]
> @godsmack321 FYI workaround for steering button in [this docs](SteeringButtonWorkaroundAA.md). Not the perfect solution, but it should do the job for this moment.

URL seems invalid in last reply.
https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/blob/main/SteeringButtonWorkaroundAA.md
