### ISSUE TITLE
Andriod Auto Alert keep poping up

### ISSUE THREAD

**Issue by mfchin96** [xeon1989/Proton-X50-APK-Installer-ATLAS#72]
Hi, how to get rid of the Android Auto Alert popping up while using wase? 
![20240102_103143](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/155623755/c88b226e-b5d5-4b43-9b64-372dfb042597)

**Comment by xeon1989** [comment]
You can disable the notification in Hidden Settings app.

**Comment by mfchin96** [comment]
Ok. Solved. Thx ya
