### ISSUE TITLE
Not installed for this user

### ISSUE THREAD

**Issue by ky960310** [xeon1989/Proton-X50-APK-Installer-ATLAS#73]
Hi xeon, good day.
This morning I ran the uninstalled script after that i reinstalled the app I want, I found out only equalizer fail to install in my ihu. Log file stated it already install but in my ihu it say not installed for this user, do u know how to fix it?

I tried to uninstall and reinstall again, still the same problem.
After that i tried reinstalled again ( this time i skipped to install equalizer ), install other app are success, then i went to hidden setting took a look, i found out equalizer cannot be uninstall also.

![image](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/131019179/ed90257b-6e45-4c07-8545-7908c8a9db93)

**Comment by xeon1989** [comment]
Hi, KY, what do you see if you tap open Equilizer app in All app list from your screenshot?
Also, try show me content of /system/app., it should be in Log file.

**Comment by ky960310** [comment]
> Hi, KY, what do you see if you tap open Equilizer app in All app list from your screenshot?
> 
> Also, try show me content of /system/app., it should be in Log file. 

Hello xeon, thank you for your quick reply. 

![image](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/131019179/81be6986-470c-4e08-b4eb-06df08423e9e)
![image](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/131019179/d1c1075a-d0e0-40de-aa95-c10cdd2b1042)
![image](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/131019179/367d09bd-a66d-43ab-b7c9-03113b3634e2)
![image](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/131019179/5886ef87-546f-427e-95c9-d253091a670c)

I've no idea how to fix it. 
This morning I only uninstall the autokit with your only uninstall autokit script, after that use your custom script to install the x90 autokit by proton, then i uninstall all the app and reinstall again, but only the equalizer did not install successful.

**Comment by xeon1989** [comment]
It seems the Equalizer app are not installed due to itself not uninstalled correctly.
Could you try this and let me know if it helps.
Just plug it in USB, wait until Android native setting shows up.
Then check the Apps and see if Equalizer still there. 
Send me log if it's not helping. 

[uninstall equalizer all user.zip](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/files/14168809/uninstall.equalizer.all.user.zip)


Note: you need to manually reboot if you want to run other scripts later.

**Comment by ky960310** [comment]
> It seems the Equalizer app are not installed due to itself not uninstalled correctly.
> 
> Could you try this and let me know if it helps?
> 
> Just plug it in USB, wait until Android native setting shows up.
> 
> Then check the Apps and see if Equalizer still there. 
> 
> Send me log if it's not helping. 
> 
> 
> 
> [uninstall equalizer all user.zip](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/files/14168809/uninstall.equalizer.all.user.zip)
> 
> 
> 
> 
> 
> Note: you need to manually reboot if you want to run other scripts later. 

Hi xeon. I downloaded the files and extracted the b832bcxxxx into my pendrive. After plug it in usb,there are no wireless charge, hidden setting screen show up. It only pop up the video, photo screen. The script is not working 🥲 
There's no log file created in the usb.  Thanks

**Comment by xeon1989** [comment]
My mistake, I had duplicated .sh in file name for High spec IHU.
Please try again. 

[uninstall equalizer all user.zip](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/files/14174684/uninstall.equalizer.all.user.zip)

**Comment by ky960310** [comment]
> My mistake, I had duplicated .sh in file name for High spec IHU. Please try again.
> 
> [uninstall equalizer all user.zip](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/files/14174684/uninstall.equalizer.all.user.zip)

Hi. The script is working now. But the equalizer in still in the app list Not installed for this user :(

here's the log file: 
[outputUninstallEqualizer_1707194470.txt](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/files/14174786/outputUninstallEqualizer_1707194470.txt)

Thank you.

**Comment by ky960310** [comment]
Hi xeon. I tried Silentshadow uninstall script just now, the equalizer app had been removed successfully.

Thank you xeon for the help and sorry for the inconvenience caused.

**Comment by xeon1989** [comment]
Hi KY, I noticed that there is FEqualizer.apk somehow sesat in /system/app directory.
This could be the cause of Equalizer app not install properly, causes the uninstallation failed.
Since Silentshadow uninstall script helps the uninstallation, it should also cleaned off that file. 
Good to hear it's now ok! :)
