### ISSUE TITLE
Query for installing atlas 

### ISSUE THREAD

**Issue by brianip86** [xeon1989/Proton-X50-APK-Installer-ATLAS#74]
Hello, I am new to this.
My system  version is SW0SXRA0812H5170.00013, can I update to new version?
Thanks.
Brian

**Comment by xeon1989** [comment]
That looks like earlier version of ATLAS. 
If you just wanted to upgrade to latest ATLAS OS, you may visit SC for them to upgrade for you.
If you wanted to upgrade to 617 for sideloading apps, I do not have experience to upgrade from this particular version.
