### ISSUE TITLE
X90 carkit apk

### ISSUE THREAD

**Issue by bizdatech** [xeon1989/Proton-X50-APK-Installer-ATLAS#75]
Hi xeon Chris.

Not sure u there have sauce for x90 carkit apk at lease can have a new updates for our x50 series of ur sideload.

**Comment by xeon1989** [comment]
Hi, I do not plan to include X90 autokit.
It's not design for X50, it's not even accessible once quit the app.
If one wants to have that instead of Carlinkit autokit, simply replace it in /app folder of the script.
