### ISSUE TITLE
Good news for Autokit

### ISSUE THREAD

**Issue by jctang1028** [xeon1989/Proton-X50-APK-Installer-ATLAS#76]
I found that the latest Autokit version (not the x90 version, is carlinkit official version) can use steering button without connect car Bluetooth, just change:

1. the “audio channel” to “box”,
2. “Microphone” setting recommend change to “phone” or “box” (for answering call purpose if you receive call with connect autokit)

The steering button can be used without connect car Bluetooth and without go to “Media”

Official Apk download link (the China version Carlinkit website : 

https://omo-oss-file.thefastfile.com/portal-saas/new2022022514431637379/cms/file/da086b85-01c4-4991-aace-4c5b5ae638a9.apk

**Comment by xeon1989** [comment]
Hi, I bought CCPA and tested latest Autokit, the steering button works indeed!
I will update the scripts with this Autokit APK.
Thanks for letting me know!

**Comment by jctang1028** [comment]
Yes, it also works for CarPlay

**Comment by vibrain-g** [comment]
can I just replace the old file of autokit version in atlas installation script with latest reinstall script?

![Screenshot 2024-02-17 173719](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/124857794/0b29296c-1829-4090-a428-8bf515590dd8)

**Comment by xeon1989** [comment]
Yes, but you need to also rename the .apk file and replace .so files in lib folder.

**Comment by vibrain-g** [comment]
Thank you bro. 👍

**Comment by xeon1989** [comment]
Wait - why do you need to replace it? Simply download the latest script and it already contains latest Autokit.

**Comment by vibrain-g** [comment]
😅 i thought that script not updated yet considering you might be busy with your new baby. Anyway, i manage to flash and install apps related successfully. Thank you bro.

But several issue occur eg:
1) sound system not so boom just like gkui.
2) wireless AA using ccpa still lag just like on gkui. Any setting i need to change?

**Comment by xeon1989** [comment]
1. Not much thing you can do about it other than downgrade to GKUI, which is not possible given that lack of Std/Exec variant firmware. Perhaps try Equalizer app?
2. If you already connected to 5Ghz wifi, try reduce resolution to 16xx amd 25fps.
3. Disable notification of Spotify in Hidden Settings. You might want to disable the same for HUR too.
