### ISSUE TITLE
HUR and Carlinkit Dongle for Android Auto

### ISSUE THREAD

**Issue by shams4883** [xeon1989/Proton-X50-APK-Installer-ATLAS#77]
If I have Carlinkit Dongle (CCPA) and Autokit app installed in Proton X50 (Flagship), do I need to have HUR (Headunit Reloaded) app installed to access Android Auto? I want to uninstall HUR to avoid frequent popping up of setup screen!

**Comment by xeon1989** [comment]
No, HUR is not needed for AA functionalities in Autokit.
You can disable Android Auto in Hidden Settings app.

**Comment by shams4883** [comment]
Thanks a lot, Chris!!! Such a quick reply!!! 
Good wishes for your new family member!!!
