### ISSUE TITLE
Script doesn't run when the USB is plugged into x50 IHU 

### ISSUE THREAD

**Issue by calvinchengkw** [xeon1989/Proton-X50-APK-Installer-ATLAS#78]
Hi, I downloaded the files into a FAT32 formatted usb and plugged it into the x50 IHU according to the instructions. Nothing seemed to happen after the usb drive with the files was plugged in and nothing was downloaded. My x50 is a late 2023 model. Is this a known issue/is there a workaround? Thanks for this!

**Comment by PeterRob** [comment]
From the Readme ''A script installing a set of apps that is currently working only in Proton X50 IHU running on ATLAS version 617 / 618'' Have you confirmed your version?

**Comment by xeon1989** [comment]
> From the Readme ''A script installing a set of apps that is currently working only in Proton X50 IHU running on ATLAS version 617 / 618'' Have you confirmed your version?

Script were tested on version  617 and it should works the same in 618. 
In case you having any issue, feel free to open a new Issue.
