### ISSUE TITLE
Google Map issue

### ISSUE THREAD

**Issue by SkyDiver7199** [xeon1989/Proton-X50-APK-Installer-ATLAS#8]
Hi, 

#1 
It appears that if I play Spotify while using Google Maps, the navigation voice will mute. I need to force stop Spotify for the voice to come back

#2 
Cannot sign in account for Google Maps. Even when I signed in account in settings, still won't sync here for the map

**Comment by SkyDiver7199** [comment]
Now there's no voice even when Spotify isn't playing..

**Comment by SkyDiver7199** [comment]
Just want to know, does anyone else have this issue or it's just me? 

Navigating without voice requires constant attention, so it pretty much render the app unusable for me..

**Comment by nyzam81** [comment]
mine works fine both apps.. Waze and Google map
