### ISSUE TITLE
Not working on geely coolray 2024

### ISSUE THREAD

**Issue by datanner19** [xeon1989/Proton-X50-APK-Installer-ATLAS#80]
after pluging the usb on the passenger side of the geely coolray 2024 nothing happens

**Comment by xeon1989** [comment]
Hi, the script only works for Proton X50, which is rebadge of Geely Coolray 2018 I think. 
I do receives positive feedback for the script in older Coolray, but it won't works in latest one since the IHU is not the same.

**Comment by datanner19** [comment]
thank you for the answer
is there any way to make it work on the coorlay 2024
