### ISSUE TITLE
S70 @ X90 IHU

### ISSUE THREAD

**Issue by TPATMkE** [xeon1989/Proton-X50-APK-Installer-ATLAS#81]
Hi there, just wondering will it worked on S70 or X90? Would like to try it but worry if it will brick my IHU, so I'm asking first. Thanks for the hack anyway!

**Comment by xeon1989** [comment]
No, it will not works, and will not brick you IHU too since it is not doing anything in your IHU.

**Comment by TPATMkE** [comment]
Noted with thanks ~
