### ISSUE TITLE
S70 guide

### ISSUE THREAD

**Issue by xDualBladerZ** [xeon1989/Proton-X50-APK-Installer-ATLAS#84]
Hi @xeon1989 , would you happen to know what I could start with if I plan to explore a solution and experiment on my S70? I know this doesn't work particularly on S70 but just curious what I should look for. I have coding backgrounds and understood that this particular solution seemed requires to match the folder to execute the script. Was wondering if you could point me to a direction to get things started, I've been trying to dig things around with no luck.

**Comment by xeon1989** [comment]
Hi, it would be handy to have either a copy of firmware, or dump the firmware out from IHU for you to find loop hole or backdoor.
Logging (logcat) also helps. 
Not to forget, developer tools.

**Comment by xDualBladerZ** [comment]
Thanks! I will try to see if I could find a firmware.

**Comment by xDualBladerZ** [comment]
I managed to find a screen which shows 'Please enter secret code.'. Couldn't figure out the code though hahaha

**Comment by Warcheif81** [comment]
its password is dy5391

**Comment by xDualBladerZ** [comment]
Woah, nice one!

**Comment by xDualBladerZ** [comment]
> its password is dy5391

Woah, nice one! Thanks @Warcheif81

**Comment by Warcheif81** [comment]
Since S70 still didnt get any official OTA software update yet,there still no available user-release software version available in ACOTECH server to download..

Below link is the user-debug software version for S70 that i already crackdown from acotech server for you guys to  decompile and study it..Its software structure and hardware kernel mostly identical with X90...Hopefully its can help you guys.

https://drive.google.com/file/d/1R0Ph_yV7XnyNLbEzmuMI7ut9xuoW04iS/view?usp=drivesdk

I will approve your access to that file later...TQ bro Chris for your contribution to X50 owners and ri eally appreciate it and hoefully you can help other proton models also ..👍👍

**Comment by xDualBladerZ** [comment]
Thanks both of you @xeon1989 & @Warcheif81 !

**Comment by Warcheif81** [comment]
@xDualBladerZ you need to use proper tools to decompile for extracting that firmware files,you can search or google which tool suit for your purpose...S70 atlas OS is customised from core Android 9 with common system and Vendor files structure and also supported kernals required with the hardware.

![IMG-20240204-WA0034](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/124855043/6f2817f9-e2c1-4321-ab08-3aac3927ca91)

**Comment by afzafri** [comment]
Keep seeing people sideloading in the S70 group, so surely there’s a way. But they are currently selling as a service to do the installation… would be happy to contribute and help with anything

**Comment by ruzaini88** [comment]
> I managed to find a screen which shows 'Please enter secret code.'. Couldn't figure out the code though hahaha

Hi @xDualBladerZ can you teach how you managed to enter that screen? I would like to study on this sideloading stuff.

**Comment by velossitymfs993** [comment]
Hi @xDualBladerZ may I know how do you trigger that keypad to enter the engineering mode of the IHU?

**Comment by city2beach** [comment]
Proton seems to lock down the engineering mode, there is no way to sideload? Did any of you did it?

**Comment by velossitymfs993** [comment]
> Proton seems to lock down the engineering mode, there is no way to sideload? Did any of you did it?

None at the moment. It seems that to enable engineer_local command must go through via server command which in this case being controlled by AcoTect. Once we can enable this command, then only we can trigger the engineering mode
