### ISSUE TITLE
Verification failed when try to downgrade from 644 to 617

### ISSUE THREAD

**Issue by AlvinC9** [xeon1989/Proton-X50-APK-Installer-ATLAS#85]
It failed when i try to downgrade it 🥲

![IMG_6792](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/169271682/9f190b07-b710-4c17-8285-a1f4df1627cc)

![IMG_6793](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/169271682/71763df9-a877-4bb4-b17e-c4328a8fe8af)

![IMG_6794](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/169271682/0fc87db5-a402-4563-8ab0-c28a75957d64)

**Comment by xeon1989** [comment]
Hi, could it be the file corrupted?
Could you please try to redownload and copy to USB drive again?

**Comment by AlvinC9** [comment]
> Hi, could it be the file corrupted? Could you please try to redownload and copy to USB drive again?

Still same

**Comment by xeon1989** [comment]
Please try to do checksum on the downloaded file.
Make sure it's the same as mentioned in another repo here.
https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade
