### ISSUE TITLE
Car launcher notification 

### ISSUE THREAD

**Issue by Jamesryan1027** [xeon1989/Proton-X50-APK-Installer-ATLAS#86]
hi bro. May I ask you a question? how can i get the notification center binding up to car launcher? because evertime when I start car. the car launcher need to restart settings access notification. May I know have how to issues  this? Thank you help😅
![20240112_191120](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/assets/127386272/710009a9-9dbb-42f1-8693-71bcd460fcd5)

**Comment by xeon1989** [comment]
Hi, sorry but I am not using car launcher. I do not know how to fix this.
