### ISSUE TITLE
Few custom app to uninstall

### ISSUE THREAD

**Issue by Louis110894** [xeon1989/Proton-X50-APK-Installer-ATLAS#88]
Hi Xeon,
I have few custom apps that need to uninstall but I have read your other related topics but I still unable to uninstall certain apps.
apps: com.vanced.android.apps.youtube.music
package: hutroops.com.vanced.android.apps.youtube.music

apps: app.revanced.android.gms
package: hutroops.app.revanced.android.gms/

apps: com.autolauncher.motorcar.free
package: hutroops.com.autolauncher.motorcar.free

These are the apps that I need to uninstall.

Please guide me.

Thanks.

**Comment by xeon1989** [comment]
[ATLAS_617_618_uninstall_Louis110894.zip](https://github.com/user-attachments/files/15737535/ATLAS_617_618_uninstall_Louis110894.zip)

Try this..
Take note that it only works if you install the app by following my script.

**Comment by Louis110894** [comment]
Hi Xeon1989,
The script works fine. 
Thanks for the support.
