### ISSUE TITLE
Uninstall specific app script

### ISSUE THREAD

**Issue by ky960310** [xeon1989/Proton-X50-APK-Installer-ATLAS#89]
Hello Xeon, how are you?

I follow your tutorial how to create uninstall script for specific app. I would like to uninstall smart tube app only.
But the file is not running after my members plug the usb in.
can u help me take a look what is the problem ? thanks!
[unintsall smart tube.zip](https://github.com/user-attachments/files/16229943/unintsall.smart.tube.zip)

**Comment by xeon1989** [comment]
Hi Khay Yin,

1. In line 16, the directory of APK to delete are different in both std and fs.
Please verify which is the correct directory. 
If your member follow my guide to install SmartTube, it should be the one with "hutroops.". 

![image](https://github.com/user-attachments/assets/e76ebfca-9ec3-4fc8-b601-a7cfbe1abd4b)

2. File name of both std and fs script is having duplicated file extension, ended with 2 ".sh".
This might be your Folder Options is hiding extension for known file type. 
Just remove the extra ".sh" should fix it. 

![image](https://github.com/user-attachments/assets/bfb0f1e6-4a96-41f7-9569-f1416f161dcc)

**Comment by ky960310** [comment]
> Hi Khay Yin,
> 
> 
> 
> 1. In line 16, the directory of APK to delete are different in both std and fs.
> 
> Please verify which is the correct directory. 
> 
> If your member follow my guide to install SmartTube, it should be the one with "hutroops.". 
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/e76ebfca-9ec3-4fc8-b601-a7cfbe1abd4b)
> 
> 
> 
> 2. File name of both std and fs script is having duplicated file extension, ended with 2 ".sh".
> 
> This might be your Folder Options is hiding extension for known file type. 
> 
> Just remove the extra ".sh" should fix it. 
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/bfb0f1e6-4a96-41f7-9569-f1416f161dcc)
> 
> 
> 
> 
> 
> 

Thank you so much for your reply Xeon ❤️❤️❤️ Last question, can i put standard/exe & premium/flagship unintall script into the same folder same as what u did to the only uninstall Autokit script last time? Because I can't ask them one by one their car is which variant 😅

**Comment by xeon1989** [comment]
Yes you can.
