### ISSUE TITLE
Android Auto Lag

### ISSUE THREAD

**Issue by yushen0212** [xeon1989/Proton-X50-APK-Installer-ATLAS#9]
Dear all,

My Atlas is running at 617. I sideloaded all the apps as per the instructions.

Everything works fine (Waze, Spotify, Google map) except Android Auto with Cable.

Once I on AA, my car location on waze doesn't move accordingly to a real live location. Sliding the app interface also need more than 3 seconds.

**Comment by muncheno** [comment]
What is your setting on the graphic setting in the HUR?
Make sure you off -> "Enable software decoder".
Try 720p (1280x720) resolution and with Pixel Density around ~135 (for split screen or around ~160 for widescreen).

Additionally, what your phone Android Auto version now?
The above setting is more of my preference for coolwalk.

**Comment by nyzam81** [comment]
for AA Coolwalk do you have the latest update or just sideload on your phone. tried yesterday and it was too laggy had to downgrade to google official release from playstore

**Comment by yushen0212** [comment]
> What is your setting on the graphic setting in the HUR? Make sure you off -> "Enable software decoder". Try 720p (1280x720) resolution and with Pixel Density around ~135 (for split screen or around ~160 for widescreen).
> 
> Additionally, what your phone Android Auto version now? The above setting is more of my preference for coolwalk.

Thanks man. I off the enable software decoder already.

**Comment by yushen0212** [comment]
> for AA Coolwalk do you have the latest update or just sideload on your phone. tried yesterday and it was too laggy had to downgrade to google official release from playstore

Yea. I'm having the latest version of AA as of now. Should be the issue above.

**Comment by nyzam81** [comment]
got 2 phones on AA 8.86.0424-release and 8.9.630603-release, so far no lag.
