### ISSUE TITLE
Atlas X50 RC not running

### ISSUE THREAD

**Issue by EwanZaidi** [xeon1989/Proton-X50-APK-Installer-ATLAS#90]
This script is not running on Atlas for X50 RC Premium

**Comment by EwanZaidi** [comment]
After i plug in my usb into the car, it pop up:  USB device detected, please choose media...but nothing happened

**Comment by Warcheif81** [comment]
X50_RC 2024 IHU using different hardware and Atlas OS version with X50_RA...Installation script for X50_RA cant be use with that X50_RC....For X50_RC its only compatible with our community build installater file which is same build for X90 & S70 to carry out apps sideload...TQ..

https://chat.whatsapp.com/KkusevXd5ot5djZ8wPTV07

**Comment by EwanZaidi** [comment]
Is there any way I can get the RC script?

**Comment by xeon1989** [comment]
The script does not support X50 RC.
