### ISSUE TITLE
Newpipe showing network error

### ISSUE THREAD

**Issue by JP213213** [xeon1989/Proton-X50-APK-Installer-ATLAS#91]
Hi anyone faced this issue, tried to play video on newpipe but keep showing network error. Heard there’s an update for newpipe?

**Comment by simble-wang** [comment]
I met the same issue even after  a recent update

**Comment by ky960310** [comment]
> Hi anyone faced this issue, tried to play video on newpipe but keep showing network error. Heard there’s an update for newpipe?

Yes. There's a new version of Newpipe. Attached is the latest newpipe installer. 
The script will uninstall the previous newpipe and reinstall the new one. TQ

[latest newpipe installer ky.zip](https://github.com/user-attachments/files/16744776/latest.newpipe.installer.ky.zip)
