### ISSUE TITLE
Cannot connect Andoird Auto Wireless

### ISSUE THREAD

**Issue by raedebug** [xeon1989/Proton-X50-APK-Installer-ATLAS#92]
I am not able to connect my Andrid Auto via Bluetooth and WiFi. I tried Bluetooth pairing with my X50, WiFi and Personal Hotspot but nothing work. Nothing happened when I click "WiFi" from the HUR AA and the only possible way is USB but connection is not stable. How do I connect my phone to HUR AA wireless?

**Comment by xeon1989** [comment]
Based on my experience, AA wireless with HUR consume too much power than my liking.
If you want to try your own:

1. On your Android phone - Settings - search "Android Auto", open. 
2. Spam "version" until it enables Developer mode
3. Settings (three dots) on top right - Start Headunit Server
4. IHU connect phone's hotspot
5. IHU - HUR (Android Auto) - tap Wifi

Those steps needed for first setup only as far as I know, the next time you just need step 5. (need confirmation by other HUR Wireless users)

Personally I prefer Carlinkit, for the sake of steering button and more seemless AA wireless. 

Let me know if you need further info.
