### ISSUE TITLE
Autokit APK for X50 RC

### ISSUE THREAD

**Issue by JasonWalao** [xeon1989/Proton-X50-APK-Installer-ATLAS#93]
I want to install Autokit APK for my new X50 RC. But some hacker community sells the package alongside with others APK and quite expensive (RM150+), and they only available for Face to Face Installation, which I'm not so free. Overall I feel its a bit red flag for me because I just want Autokit, that's all. I kindly request whether Xeon can make a scripts for it or any other way to let me install it. Thank you and sorry for bothering.

**Comment by kanasite** [comment]
I think @xeon1989 mentioned this doesn't support X50 RC

https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/issues/90#issuecomment-2359702693
