### ISSUE TITLE
Newpipe app cannot play 

### ISSUE THREAD

**Issue by 5Y4Z0NE** [xeon1989/Proton-X50-APK-Installer-ATLAS#94]
I already reinstalled newpipe app using the provided reinstaller its not working for me. Can you fix it. Thank you sir. FS user here

**Comment by xeon1989** [comment]
Hi, I could not recall if I uploaded reinstaller of newpipe in this repository.
Could you please provide the link of the reinstaller?

**Comment by Jordan112004** [comment]
Please fix this content unavailable on newpipe please!!!!

**Comment by xeon1989** [comment]
Hi @Jordan112004, as I no longer uses newpipe in X50 IHU, I could not responsibly maintain the working version for something I am not using nor confirming it work for long period.
Therefore I have removed Newpipe from my installer. 
Kindly confirm the working Newpipe version and install it with [Custom App Script](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/blob/main/Install_Your_Own_Apps.md).
