### ISSUE TITLE
app installation problem

### ISSUE THREAD

**Issue by brian9939** [xeon1989/Proton-X50-APK-Installer-ATLAS#96]
How do i add an Equalizer app to my atlas IHU? i have previously flashed and did the initial steps but the apps installed does not include an equalizer app. But when i followed all the steps, there was no reaction to my ihu when i plug in the usb port. I have 2 contents : "app" and "b832bc61472727635baffcf25dd28e9f239273e2" in my pendrive when plugging in. There was the USB detected pop up too. What went wrong or where shall i find the equalizer app?

**Comment by xeon1989** [comment]
Hi Brian, did you just downgraded from v644 to v617.
Could you please confirm the IHU version again?
I think there is a few reported that latest v644 IHU no longer allows you to downgrade.
Older version not reflected despite after choosing the correct .zip file, however I couldn't verify this.

**Comment by brian9939** [comment]
its not the latest version, i have previously downgraded it to v617 for apple carplay (my x50 is july 2023).

Or could it be missing lib file? i did all the steps but i didnt see lib file. then i thought it is okay since you wrote can ignore steps 10-11 if dont have lib.

**Comment by xeon1989** [comment]
Send me the APK, let me try generate the script.

**Comment by brian9939** [comment]
the app is called flat equalizer found in Apkpure, i think you can app equalizer app for general app installation script because x50 audio sucks haha, we badly need it

**Comment by ky960310** [comment]
> the app is called flat equalizer found in Apkpure, i think you can app equalizer app for general app installation script because x50 audio sucks haha, we badly need it

You can check it our here.
I already uploaded it on google drive: https://drive.google.com/drive/folders/1kEk9SON97vIUn-6fVHYi-co680JwUZp0
