### ISSUE TITLE
Disable Joox

### ISSUE THREAD

**Issue by heythorn** [xeon1989/Proton-X50-APK-Installer-ATLAS#97]
Anyone know the app name to disable JOOX app?

I've tried **pm disable com.malaysia.joox**

I added the above line rename the file to match the hash.
I guess **com.malaysia.joox** is not correct.

**Comment by xeon1989** [comment]
It is `pm disable com.malaysia.joox` indeed.

**Comment by heythorn** [comment]
Thanks. There's a ready script in optimization
